/**
 * 大湾区亲子活动数据
 * 坐标为近似位置（WGS-84），详情页提供地图导航链接以名称搜索为准。
 * 字段: n=名称, c=分类, city=城市, lat/lng=坐标, d=简介,
 *       age=适合年龄, free=是否免费, io=室内/户外(indoor/outdoor/both),
 *       addr=地址, tags=标签, season=采摘季节(仅农场)
 */
const ACTIVITIES = [
  // ============ 深圳 ============
  { n: "深圳湾公园", c: "park", city: "深圳", lat: 22.517, lng: 113.947, d: "滨海长廊，适合骑行、放风筝、看候鸟，海景开阔。", age: "0-14", free: true, io: "outdoor", addr: "南山区滨海大道", tags: ["海景", "骑行", "观鸟"] },
  { n: "莲花山公园", c: "park", city: "深圳", lat: 22.551, lng: 114.060, d: "市中心大草坪与风筝广场，山顶可俯瞰市民中心。", age: "0-14", free: true, io: "outdoor", addr: "福田区红荔路6030号", tags: ["草坪", "风筝"] },
  { n: "香蜜公园", c: "park", city: "深圳", lat: 22.552, lng: 114.026, d: "空中栈道、荔枝林与儿童游乐区，婚礼堂旁花田好拍照。", age: "0-12", free: true, io: "outdoor", addr: "福田区农园路30号", tags: ["栈道", "花田"] },
  { n: "人才公园", c: "park", city: "深圳", lat: 22.518, lng: 113.935, d: "环湖步道与夜景灯光，紧邻深圳湾，适合傍晚遛娃。", age: "0-14", free: true, io: "outdoor", addr: "南山区科苑南路", tags: ["湖景", "夜景"] },
  { n: "福田红树林生态公园", c: "hiking", city: "深圳", lat: 22.524, lng: 114.005, d: "红树林湿地科普，栈道观鸟，冬季候鸟季最佳。", age: "3-14", free: true, io: "outdoor", addr: "福田区新洲路南端", tags: ["湿地", "观鸟", "科普"] },
  { n: "深圳市儿童乐园", c: "playground", city: "深圳", lat: 22.554, lng: 114.023, d: "公益性儿童乐园，摩天轮与多种机动游戏，票价亲民。", age: "2-12", free: false, io: "outdoor", addr: "福田区侨香路", tags: ["机动游戏", "摩天轮"] },
  { n: "深圳欢乐港湾", c: "playground", city: "深圳", lat: 22.535, lng: 113.891, d: "湾区之光摩天轮、滨海草坪与大型户外儿童乐园。", age: "0-14", free: true, io: "outdoor", addr: "宝安区海天路", tags: ["摩天轮", "滨海"] },
  { n: "深圳图书馆", c: "library", city: "深圳", lat: 22.547, lng: 114.056, d: "市中心地标图书馆，少儿馆藏丰富，周末有亲子活动。", age: "0-16", free: true, io: "indoor", addr: "福田区福中一路2001号", tags: ["少儿区", "空调"] },
  { n: "深圳少年儿童图书馆", c: "library", city: "深圳", lat: 22.564, lng: 114.108, d: "专为儿童设计的图书馆，绘本区与故事会活动多。", age: "0-14", free: true, io: "indoor", addr: "罗湖区太宁路1号", tags: ["绘本", "故事会"] },
  { n: "深圳博物馆（历史民俗馆）", c: "museum", city: "深圳", lat: 22.543, lng: 114.062, d: "免费市博物馆，深圳改革开放史与民俗展，周末常有儿童讲解活动。", age: "4-16", free: true, io: "indoor", addr: "福田区市民中心A区", tags: ["历史"] },
  { n: "深圳野生动物园", c: "zoo", city: "深圳", lat: 22.593, lng: 113.985, d: "放养式动物园，可近距离看长颈鹿、火烈鸟，有动物表演。", age: "1-14", free: false, io: "outdoor", addr: "南山区西丽湖路4065号", tags: ["动物", "投喂"] },
  { n: "深圳欢乐谷", c: "themepark", city: "深圳", lat: 22.540, lng: 113.977, d: "大型主题乐园，过山车与儿童区兼备，暑期有夜场。", age: "3-16", free: false, io: "both", addr: "南山区侨城西街18号", tags: ["过山车", "演出"] },
  { n: "世界之窗", c: "themepark", city: "深圳", lat: 22.535, lng: 113.973, d: "世界地标微缩景观，晚间有大型演出与烟火。", age: "4-16", free: false, io: "outdoor", addr: "南山区深南大道9037号", tags: ["景观", "演出"] },
  { n: "东部华侨城", c: "themepark", city: "深圳", lat: 22.606, lng: 114.283, d: "山地主题乐园，茶溪谷+大侠谷，缆车与山间小火车。", age: "4-16", free: false, io: "outdoor", addr: "盐田区大梅沙东部华侨城", tags: ["缆车", "山景"] },
  { n: "大梅沙海滨公园", c: "beach", city: "深圳", lat: 22.596, lng: 114.313, d: "免费城市沙滩，设施成熟，旺季需预约。", age: "0-14", free: true, io: "outdoor", addr: "盐田区盐梅路9号", tags: ["沙滩", "需预约"] },
  { n: "较场尾海滩", c: "beach", city: "深圳", lat: 22.588, lng: 114.510, d: "大鹏民宿海滩村，沙质细，适合亲子过夜短途游。", age: "0-14", free: true, io: "outdoor", addr: "大鹏新区较场尾", tags: ["民宿", "沙滩"] },
  { n: "西涌沙滩", c: "beach", city: "深圳", lat: 22.478, lng: 114.548, d: "深圳最长海滩，暗夜社区可观星，水清人少。", age: "3-16", free: false, io: "outdoor", addr: "大鹏新区南澳西涌", tags: ["观星", "沙滩"] },
  { n: "梧桐山国家级风景区", c: "hiking", city: "深圳", lat: 22.586, lng: 114.209, d: "深圳第一峰，适合大童登山，秀桐道较缓可推车段少。", age: "6-16", free: true, io: "outdoor", addr: "罗湖区梧桐山", tags: ["登山", "云海"] },
  { n: "塘朗山郊野公园", c: "hiking", city: "深圳", lat: 22.559, lng: 113.985, d: "缓坡郊野绿道，山顶可望深圳湾，亲子入门徒步线。", age: "4-14", free: true, io: "outdoor", addr: "南山区龙珠六路", tags: ["绿道", "入门徒步"] },
  { n: "马峦山郊野公园", c: "hiking", city: "深圳", lat: 22.633, lng: 114.325, d: "深圳少有的瀑布溪谷徒步线，夏天可玩水。", age: "5-16", free: true, io: "outdoor", addr: "坪山区马峦山", tags: ["瀑布", "溪谷"] },
  { n: "光明农场大观园", c: "farm", city: "深圳", lat: 22.749, lng: 113.918, d: "奶牛示范基地，挤奶体验、喂小动物与滑草。", age: "2-12", free: false, io: "outdoor", addr: "光明区光明街道碧水路", tags: ["奶牛", "滑草"], season: "全年" },
  { n: "甘坑古镇", c: "park", city: "深圳", lat: 22.634, lng: 114.116, d: "客家小镇，小凉帽主题亲子业态，古建筑好拍照。", age: "2-12", free: true, io: "both", addr: "龙岗区甘坑社区", tags: ["古镇", "客家"] },
  { n: "杨梅坑", c: "hiking", city: "深圳", lat: 22.545, lng: 114.606, d: "海边骑行绿道与鹿嘴山庄步道，山海相接。", age: "4-16", free: true, io: "outdoor", addr: "大鹏新区南澳杨梅坑", tags: ["骑行", "海景"] },
  { n: "深圳海上世界", c: "park", city: "深圳", lat: 22.485, lng: 113.917, d: "明华轮广场音乐喷泉，滨海餐饮街区，傍晚遛娃佳。", age: "0-12", free: true, io: "outdoor", addr: "南山区蛇口望海路", tags: ["喷泉", "餐饮"] },

  // ============ 广州 ============
  { n: "长隆野生动物世界", c: "zoo", city: "广州", lat: 23.001, lng: 113.327, d: "亚洲顶级动物园，考拉、熊猫齐全，小火车穿越车行区。", age: "1-16", free: false, io: "outdoor", addr: "番禺区汉溪大道东299号", tags: ["熊猫", "小火车"] },
  { n: "长隆欢乐世界", c: "themepark", city: "广州", lat: 23.004, lng: 113.328, d: "大型游乐园，垂直过山车闻名，儿童区设施完善。", age: "3-16", free: false, io: "both", addr: "番禺区汉溪大道东", tags: ["过山车", "演出"] },
  { n: "长隆水上乐园", c: "waterplay", city: "广州", lat: 23.005, lng: 113.325, d: "全球客流量最大的水上乐园之一，亲子戏水区丰富。", age: "3-16", free: false, io: "outdoor", addr: "番禺区汉溪大道东", tags: ["滑道", "造浪池"] },
  { n: "广州动物园", c: "zoo", city: "广州", lat: 23.140, lng: 113.302, d: "市区老牌动物园，票价亲民，地铁直达。", age: "1-12", free: false, io: "outdoor", addr: "越秀区先烈中路120号", tags: ["市区", "亲民"] },
  { n: "正佳极地海洋世界", c: "zoo", city: "广州", lat: 23.132, lng: 113.327, d: "商场内的海洋馆，白鲸与企鹅，雨天遛娃好去处。", age: "1-12", free: false, io: "indoor", addr: "天河区天河路228号正佳广场", tags: ["白鲸", "室内"] },
  { n: "广州图书馆", c: "library", city: "广州", lat: 23.109, lng: 113.324, d: "花城广场地标图书馆，少儿部超大，需预约入馆。", age: "0-16", free: true, io: "indoor", addr: "天河区珠江东路4号", tags: ["少儿部", "地标"] },
  { n: "广州少年儿童图书馆", c: "library", city: "广州", lat: 23.127, lng: 113.267, d: "专门的少儿图书馆，分龄阅读区与常设故事活动。", age: "0-14", free: true, io: "indoor", addr: "越秀区中山四路42号", tags: ["分龄", "故事会"] },
  { n: "广东省博物馆", c: "museum", city: "广州", lat: 23.113, lng: 113.323, d: "月光宝盒造型省博，恐龙化石与海洋展厅孩子最爱。", age: "3-16", free: true, io: "indoor", addr: "天河区珠江东路2号", tags: ["恐龙", "需预约"] },
  { n: "广东科学中心", c: "museum", city: "广州", lat: 23.043, lng: 113.365, d: "亚洲特大科技馆，互动实验展项极多，可玩一整天。", age: "3-16", free: false, io: "indoor", addr: "番禺区科普路168号", tags: ["互动", "IMAX"] },
  { n: "越秀公园", c: "park", city: "广州", lat: 23.140, lng: 113.263, d: "五羊雕像所在的百年公园，湖泊山丘与大草坪。", age: "0-12", free: true, io: "outdoor", addr: "越秀区解放北路988号", tags: ["五羊", "湖景"] },
  { n: "天河公园", c: "park", city: "广州", lat: 23.126, lng: 113.365, d: "市区大型免费公园，湖边草坪适合野餐帐篷。", age: "0-12", free: true, io: "outdoor", addr: "天河区黄埔大道员村", tags: ["野餐", "草坪"] },
  { n: "海珠湖公园", c: "park", city: "广州", lat: 23.075, lng: 113.322, d: "广州塔旁的城市绿心，环湖步道平缓适合童车。", age: "0-12", free: true, io: "outdoor", addr: "海珠区新滘中路", tags: ["环湖", "花海"] },
  { n: "海珠国家湿地公园", c: "hiking", city: "广州", lat: 23.070, lng: 113.345, d: "城央湿地，果林与观鸟塔，自然教育课程丰富。", age: "3-14", free: false, io: "outdoor", addr: "海珠区新滘东路", tags: ["湿地", "自然教育"] },
  { n: "白云山风景区", c: "hiking", city: "广州", lat: 23.180, lng: 113.293, d: "羊城第一秀，缆车上山亲子友好，山顶广场开阔。", age: "3-16", free: false, io: "outdoor", addr: "白云区广园中路", tags: ["缆车", "登山"] },
  { n: "华南国家植物园", c: "park", city: "广州", lat: 23.186, lng: 113.362, d: "国家级植物园，温室群与凤梨园，自然课堂常年开放。", age: "2-14", free: false, io: "outdoor", addr: "天河区天源路1190号", tags: ["温室", "科普"] },
  { n: "广州市儿童公园", c: "playground", city: "广州", lat: 23.183, lng: 113.264, d: "免费大型儿童公园，沙池、戏水区与游乐设施分龄设置。", age: "0-12", free: true, io: "outdoor", addr: "白云区齐心路61号", tags: ["沙池", "戏水"] },
  { n: "二沙岛艺术公园", c: "park", city: "广州", lat: 23.112, lng: 113.305, d: "珠江中的安静小岛，大草坪与雕塑，适合野餐骑行。", age: "0-12", free: true, io: "outdoor", addr: "越秀区二沙岛", tags: ["草坪", "江景"] },
  { n: "广州融创乐园", c: "themepark", city: "广州", lat: 23.428, lng: 113.163, d: "花都大型乐园，另有室内滑雪场与水世界。", age: "3-16", free: false, io: "both", addr: "花都区凤凰北路", tags: ["滑雪", "水乐园"] },
  { n: "石门国家森林公园", c: "hiking", city: "广州", lat: 23.669, lng: 113.767, d: "从化天然氧吧，春赏花秋赏红叶，溪流步道。", age: "4-16", free: false, io: "outdoor", addr: "从化区温泉镇", tags: ["森林", "赏花"] },
  { n: "白水寨风景名胜区", c: "hiking", city: "广州", lat: 23.436, lng: 113.850, d: "内地落差最大瀑布之一，9999级登山步道可量力而行。", age: "5-16", free: false, io: "outdoor", addr: "增城区派潭镇", tags: ["瀑布", "登山"] },
  { n: "南沙湿地公园", c: "hiking", city: "广州", lat: 22.620, lng: 113.640, d: "珠三角候鸟天堂，坐船游湿地，冬季观鸟最佳。", age: "3-14", free: false, io: "outdoor", addr: "南沙区万顷沙镇", tags: ["观鸟", "游船"] },
  { n: "从化溪头村", c: "farm", city: "广州", lat: 23.727, lng: 113.729, d: "长寿村徒步与季节性水果采摘，夏季李子冬季砂糖橘。", age: "3-14", free: true, io: "outdoor", addr: "从化区良口镇溪头村", tags: ["采摘", "古村"], season: "6-8月李子 / 11-1月柑橘" },

  // ============ 香港 ============
  { n: "香港迪士尼乐园", c: "themepark", city: "香港", lat: 22.313, lng: 114.041, d: "亚洲经典迪士尼，冰雪奇缘园区人气高，烟花压轴。", age: "2-16", free: false, io: "both", addr: "大屿山迪士尼乐园度假区", tags: ["迪士尼", "烟花"] },
  { n: "香港海洋公园", c: "themepark", city: "香港", lat: 22.246, lng: 114.176, d: "山海主题乐园，大熊猫馆与海洋馆，缆车跨山海景震撼。", age: "2-16", free: false, io: "both", addr: "香港仔黄竹坑道180号", tags: ["熊猫", "缆车", "海洋馆"] },
  { n: "海洋公园水上乐园", c: "waterplay", city: "香港", lat: 22.247, lng: 114.180, d: "全天候临海水上乐园，室内外滑道全年开放。", age: "3-16", free: false, io: "both", addr: "南区大树湾", tags: ["滑道", "全年开放"] },
  { n: "香港科学馆", c: "museum", city: "香港", lat: 22.301, lng: 114.177, d: "互动科学展馆，能量穿梭机装置经典，儿童天地适合幼儿。", age: "2-14", free: false, io: "indoor", addr: "尖沙咀东部科学馆道2号", tags: ["互动", "亲民票价"] },
  { n: "香港太空馆", c: "museum", city: "香港", lat: 22.294, lng: 114.172, d: "蛋形建筑天文馆，天象厅球幕电影不容错过。", age: "4-14", free: false, io: "indoor", addr: "尖沙咀梳士巴利道10号", tags: ["天文", "球幕"] },
  { n: "香港历史博物馆", c: "museum", city: "香港", lat: 22.301, lng: 114.176, d: "香港故事常设展，实景街道还原老香港。", age: "5-16", free: true, io: "indoor", addr: "尖沙咀漆咸道南100号", tags: ["历史"] },
  { n: "M+ 博物馆", c: "museum", city: "香港", lat: 22.302, lng: 114.159, d: "西九文化区当代视觉文化博物馆，海旁草坪可野餐。", age: "5-16", free: false, io: "both", addr: "西九龙文化区博物馆道38号", tags: ["艺术", "海景草坪"] },
  { n: "香港湿地公园", c: "hiking", city: "香港", lat: 22.469, lng: 114.005, d: "天水围湿地保护区，观鸟屋与红树林浮桥，科普性强。", age: "3-14", free: false, io: "both", addr: "新界天水围湿地公园路", tags: ["湿地", "观鸟"] },
  { n: "香港中央图书馆", c: "library", city: "香港", lat: 22.280, lng: 114.190, d: "全港最大公共图书馆，玩具图书馆需预约。", age: "0-16", free: true, io: "indoor", addr: "铜锣湾高士威道66号", tags: ["玩具图书馆"] },
  { n: "九龙公园", c: "park", city: "香港", lat: 22.300, lng: 114.170, d: "闹市绿洲，火烈鸟池与大型儿童游乐场。", age: "0-12", free: true, io: "outdoor", addr: "尖沙咀柯士甸道22号", tags: ["火烈鸟", "游乐场"] },
  { n: "香港公园", c: "park", city: "香港", lat: 22.277, lng: 114.161, d: "中环山坡公园，观鸟园大型雀笼漫步道免费。", age: "0-12", free: true, io: "outdoor", addr: "中区红棉路19号", tags: ["观鸟园"] },
  { n: "维多利亚公园", c: "park", city: "香港", lat: 22.282, lng: 114.189, d: "港岛最大公园，游乐场与草坪，节庆花市热闹。", age: "0-12", free: true, io: "outdoor", addr: "铜锣湾兴发街1号", tags: ["草坪", "游乐场"] },
  { n: "浅水湾泳滩", c: "beach", city: "香港", lat: 22.237, lng: 114.197, d: "港岛经典泳滩，沙细浪缓，配套成熟。", age: "0-14", free: true, io: "outdoor", addr: "南区浅水湾海滩道", tags: ["泳滩", "救生员"] },
  { n: "石澳泳滩", c: "beach", city: "香港", lat: 22.231, lng: 114.253, d: "港岛东南小村泳滩，彩色小屋好拍照。", age: "2-14", free: true, io: "outdoor", addr: "南区石澳村", tags: ["泳滩", "拍照"] },
  { n: "清水湾二滩", c: "beach", city: "香港", lat: 22.281, lng: 114.297, d: "西贡清水质靓泳滩，周末家庭客多。", age: "2-14", free: true, io: "outdoor", addr: "西贡清水湾道", tags: ["水清", "泳滩"] },
  { n: "昂坪360与大佛", c: "hiking", city: "香港", lat: 22.256, lng: 113.905, d: "水晶缆车俯瞰大屿山，天坛大佛与昂坪市集。", age: "3-16", free: false, io: "both", addr: "大屿山昂坪", tags: ["缆车", "大佛"] },
  { n: "龙脊远足径", c: "hiking", city: "香港", lat: 22.245, lng: 114.238, d: "亚洲最佳市区远足径之一，山脊海景线，适合大童。", age: "7-16", free: true, io: "outdoor", addr: "港岛石澳道起步", tags: ["远足", "海景"] },
  { n: "塔门岛", c: "camping", city: "香港", lat: 22.472, lng: 114.360, d: "大草坪海岛露营胜地，看牛看海观星，需坐船。", age: "4-16", free: true, io: "outdoor", addr: "西贡塔门", tags: ["露营", "海岛"] },
  { n: "嘉道理农场暨植物园", c: "farm", city: "香港", lat: 22.432, lng: 114.117, d: "山地生态农场，动物救助站与有机农田，自然教育典范。", age: "3-14", free: false, io: "outdoor", addr: "大埔林锦公路", tags: ["生态", "动物"], season: "全年" },
  { n: "挪亚方舟主题公园", c: "themepark", city: "香港", lat: 22.352, lng: 114.059, d: "马湾1:1方舟建筑，亲子互动展馆与户外攀爬。", age: "2-12", free: false, io: "both", addr: "马湾珀欣路33号", tags: ["方舟", "互动"] },
  { n: "香港动植物公园", c: "zoo", city: "香港", lat: 22.277, lng: 114.156, d: "中环免费百年动植物公园，红毛猩猩与狐猴。", age: "0-12", free: true, io: "outdoor", addr: "中区雅宾利道", tags: ["灵长类"] },

  // ============ 澳门 ============
  { n: "澳门科学馆", c: "museum", city: "澳门", lat: 22.185, lng: 113.557, d: "贝聿铭设计的海滨科学馆，互动展厅分龄清晰。", age: "2-14", free: false, io: "indoor", addr: "澳门孙逸仙大马路", tags: ["互动", "天文馆"] },
  { n: "石排湾郊野公园与大熊猫馆", c: "zoo", city: "澳门", lat: 22.125, lng: 113.559, d: "路环山脚郊野公园，大熊猫馆票价亲民，另有动物区。", age: "0-12", free: false, io: "both", addr: "路环石排湾大马路", tags: ["熊猫", "亲民"] },
  { n: "黑沙海滩", c: "beach", city: "澳门", lat: 22.118, lng: 113.576, d: "澳门最大天然海滩，黑色海沙独特，旁有烧烤区。", age: "0-14", free: true, io: "outdoor", addr: "路环黑沙马路", tags: ["黑沙", "烧烤"] },
  { n: "龙环葡韵", c: "museum", city: "澳门", lat: 22.153, lng: 113.558, d: "五栋薄荷绿葡式别墅与湿地，展馆免费，白鹭常驻。", age: "2-12", free: true, io: "both", addr: "氹仔海边马路", tags: ["葡式建筑"] },
  { n: "氹仔中央公园", c: "park", city: "澳门", lat: 22.155, lng: 113.555, d: "氹仔居民区大公园，儿童游乐场设施新。", age: "0-10", free: true, io: "outdoor", addr: "氹仔成都街", tags: ["游乐场"] },
  { n: "二龙喉公园与松山缆车", c: "park", city: "澳门", lat: 22.200, lng: 113.548, d: "号称全球最短缆车上松山，山顶灯塔与炮台。", age: "2-12", free: true, io: "outdoor", addr: "澳门士多鸟拜斯大马路", tags: ["缆车", "灯塔"] },
  { n: "澳门海事博物馆", c: "museum", city: "澳门", lat: 22.186, lng: 113.531, d: "妈阁庙旁的航海历史博物馆，船模与互动展品。", age: "3-12", free: false, io: "indoor", addr: "妈阁上街1号", tags: ["航海", "亲民"] },
  { n: "teamLab 超自然空间", c: "indoorplay", city: "澳门", lat: 22.147, lng: 113.563, d: "威尼斯人旁沉浸式数字艺术空间，光影互动孩子着迷。", age: "2-14", free: false, io: "indoor", addr: "路氹金光大道", tags: ["光影", "沉浸式"] },

  // ============ 珠海 ============
  { n: "珠海长隆海洋王国", c: "themepark", city: "珠海", lat: 22.101, lng: 113.529, d: "世界级海洋主题乐园，鲸鲨馆与烟花汇演。", age: "1-16", free: false, io: "both", addr: "横琴新区富祥湾", tags: ["鲸鲨", "烟花"] },
  { n: "长隆宇宙飞船", c: "zoo", city: "珠海", lat: 22.104, lng: 113.532, d: "飞船造型超大室内海洋科学乐园，雨天遛娃首选。", age: "1-14", free: false, io: "indoor", addr: "横琴新区环岛东路", tags: ["室内", "海洋科学"] },
  { n: "珠海渔女与情侣路", c: "park", city: "珠海", lat: 22.259, lng: 113.590, d: "珠海地标雕像，沿海步道适合童车与滑板车。", age: "0-12", free: true, io: "outdoor", addr: "香洲区情侣中路", tags: ["海滨", "地标"] },
  { n: "珠海海滨公园", c: "park", city: "珠海", lat: 22.253, lng: 113.578, d: "老牌免费海滨公园，大草坪与儿童游乐区。", age: "0-12", free: true, io: "outdoor", addr: "香洲区情侣中路", tags: ["草坪"] },
  { n: "珠海博物馆", c: "museum", city: "珠海", lat: 22.244, lng: 113.575, d: "海滨新馆，珠海历史与海洋文化展陈，免费预约。", age: "4-16", free: true, io: "indoor", addr: "香洲区情侣路", tags: ["海洋文化"] },
  { n: "淇澳岛红树林保护区", c: "hiking", city: "珠海", lat: 22.418, lng: 113.630, d: "红树林栈道与渔村，骑行环岛亲子友好。", age: "3-14", free: true, io: "outdoor", addr: "香洲区淇澳岛", tags: ["红树林", "骑行"] },
  { n: "板樟山健身步道", c: "hiking", city: "珠海", lat: 22.263, lng: 113.560, d: "森林山脊步道与观景平台，可俯瞰珠澳两地。", age: "5-14", free: true, io: "outdoor", addr: "香洲区板樟山", tags: ["步道", "观景"] },
  { n: "香山湖公园", c: "park", city: "珠海", lat: 22.267, lng: 113.528, d: "山水相依的新公园，环湖绿道与大草坪。", age: "0-12", free: true, io: "outdoor", addr: "香洲区梅华东路", tags: ["环湖", "草坪"] },
  { n: "东澳岛", c: "beach", city: "珠海", lat: 22.014, lng: 113.710, d: "万山群岛度假海岛，南沙湾水质清澈，需乘船。", age: "3-14", free: false, io: "outdoor", addr: "万山区东澳岛", tags: ["海岛", "度假"] },
  { n: "外伶仃岛", c: "beach", city: "珠海", lat: 22.112, lng: 114.023, d: "离岛观海胜地，石景山步道可望香港，海鲜出名。", age: "4-14", free: false, io: "outdoor", addr: "万山区外伶仃岛", tags: ["海岛", "步道"] },
  { n: "珠海图书馆", c: "library", city: "珠海", lat: 22.271, lng: 113.567, d: "市级图书馆少儿区宽敞，周末讲座活动多。", age: "0-16", free: true, io: "indoor", addr: "香洲区迎宾北路", tags: ["少儿区"] },

  // ============ 佛山 ============
  { n: "千灯湖公园", c: "park", city: "佛山", lat: 23.037, lng: 113.140, d: "南海中轴水景公园，夜晚灯光秀，草坪开阔。", age: "0-12", free: true, io: "outdoor", addr: "南海区桂澜北路", tags: ["夜景", "草坪"] },
  { n: "佛山市图书馆", c: "library", city: "佛山", lat: 23.007, lng: 113.147, d: "佛山新城大型图书馆，少儿馆有专属活动空间。", age: "0-16", free: true, io: "indoor", addr: "顺德区乐从镇华康道", tags: ["少儿馆"] },
  { n: "南风古灶", c: "museum", city: "佛山", lat: 23.005, lng: 113.093, d: "五百年龙窑活文物，陶艺拉坯亲子体验。", age: "3-14", free: false, io: "both", addr: "禅城区石湾高庙路", tags: ["陶艺", "体验"] },
  { n: "西樵山风景区", c: "hiking", city: "佛山", lat: 22.930, lng: 112.960, d: "岭南名山，观音文化与山湖步道，缆车可达。", age: "4-16", free: false, io: "outdoor", addr: "南海区西樵镇", tags: ["名山", "缆车"] },
  { n: "长鹿旅游休博园", c: "themepark", city: "佛山", lat: 22.821, lng: 113.279, d: "顺德老牌亲子乐园，动物园+机动游戏+农家体验。", age: "1-14", free: false, io: "both", addr: "顺德区伦教镇", tags: ["动物", "机动游戏"] },
  { n: "顺德欢乐海岸PLUS", c: "themepark", city: "佛山", lat: 22.818, lng: 113.255, d: "水岸乐园与玛雅水公园，摩天轮夜景美。", age: "2-14", free: false, io: "both", addr: "顺德区大良街道", tags: ["水乐园", "摩天轮"] },
  { n: "亚洲艺术公园", c: "park", city: "佛山", lat: 23.019, lng: 113.124, d: "禅城水上公园，桥廊水景与大片草坪。", age: "0-12", free: true, io: "outdoor", addr: "禅城区文华北路", tags: ["水景"] },
  { n: "三水荷花世界", c: "park", city: "佛山", lat: 23.175, lng: 112.905, d: "夏季赏荷主题园，荷花季亲子写生好去处。", age: "2-12", free: false, io: "outdoor", addr: "三水区西南街道", tags: ["荷花", "夏季"] },
  { n: "盈香生态园", c: "farm", city: "佛山", lat: 22.850, lng: 112.800, d: "高明综合生态园，四季花海、采摘与机动游戏。", age: "2-14", free: false, io: "outdoor", addr: "高明区荷城街道冼村", tags: ["花海", "采摘"], season: "全年花期轮换" },
  { n: "美的鹭湖水世界", c: "waterplay", city: "佛山", lat: 22.798, lng: 112.752, d: "高明度假区水乐园，另有探索王国与温泉。", age: "3-14", free: false, io: "outdoor", addr: "高明区杨和镇", tags: ["水乐园", "度假"] },

  // ============ 东莞 ============
  { n: "松山湖景区", c: "park", city: "东莞", lat: 22.925, lng: 113.878, d: "环湖绿道骑行圣地，春季黄花风铃木刷屏。", age: "0-14", free: true, io: "outdoor", addr: "松山湖高新区", tags: ["骑行", "赏花"] },
  { n: "东莞植物园", c: "park", city: "东莞", lat: 23.005, lng: 113.745, d: "免费大型植物园，专类园与大草坪适合野餐。", age: "0-12", free: true, io: "outdoor", addr: "南城街道绿色路", tags: ["野餐"] },
  { n: "东莞市科学技术博物馆", c: "museum", city: "东莞", lat: 23.020, lng: 113.752, d: "制造业主题科技馆，机器人展项有特色。", age: "3-14", free: true, io: "indoor", addr: "南城街道元美路2号", tags: ["机器人"] },
  { n: "海战博物馆", c: "museum", city: "东莞", lat: 22.805, lng: 113.652, d: "虎门销烟与鸦片战争史，海边炮台遗址可散步。", age: "5-16", free: true, io: "both", addr: "虎门镇威远岛", tags: ["历史"] },
  { n: "银瓶山森林公园", c: "hiking", city: "东莞", lat: 22.940, lng: 114.190, d: "东莞第一峰，溪谷步道前段平缓适合亲子。", age: "4-16", free: true, io: "outdoor", addr: "谢岗镇银瓶山", tags: ["溪谷", "登山"] },
  { n: "隐贤山庄", c: "themepark", city: "东莞", lat: 22.975, lng: 113.975, d: "常平综合乐园，机动游戏与动物互动，性价比高。", age: "2-14", free: false, io: "both", addr: "常平镇丽城", tags: ["性价比", "动物"] },
  { n: "华阳湖国家湿地公园", c: "hiking", city: "东莞", lat: 23.033, lng: 113.555, d: "麻涌水乡湿地，绿道骑行与游船看夕阳。", age: "2-14", free: true, io: "outdoor", addr: "麻涌镇", tags: ["湿地", "骑行"] },
  { n: "东莞图书馆", c: "library", city: "东莞", lat: 23.019, lng: 113.752, d: "24小时自助图书馆先行者，绘本馆藏丰富。", age: "0-16", free: true, io: "indoor", addr: "南城街道新芬路", tags: ["绘本"] },
  { n: "香市动物园", c: "zoo", city: "东莞", lat: 22.965, lng: 113.836, d: "寮步中型动物园，动物表演与投喂体验，票价亲民。", age: "1-12", free: false, io: "outdoor", addr: "寮步镇药勒村", tags: ["投喂", "亲民"] },

  // ============ 中山 ============
  { n: "中山詹园", c: "park", city: "中山", lat: 22.445, lng: 113.350, d: "岭南最大私家园林，古典建筑与孝道文化。", age: "3-14", free: false, io: "both", addr: "南区北台村", tags: ["园林", "古典"] },
  { n: "孙中山故里旅游区", c: "museum", city: "中山", lat: 22.410, lng: 113.443, d: "翠亨村故居与纪念馆，历史人文研学线路。", age: "5-16", free: true, io: "both", addr: "南朗街道翠亨村", tags: ["历史", "研学"] },
  { n: "金钟湖公园", c: "park", city: "中山", lat: 22.530, lng: 113.400, d: "环湖步道与儿童乐园，中山市民后花园。", age: "0-12", free: true, io: "outdoor", addr: "东区金钟大道", tags: ["环湖"] },
  { n: "紫马岭公园", c: "park", city: "中山", lat: 22.518, lng: 113.405, d: "老牌市政公园，鸟语林与大片绿地。", age: "0-12", free: true, io: "outdoor", addr: "东区中山五路", tags: ["鸟语林"] },
  { n: "中山纪念图书馆", c: "library", city: "中山", lat: 22.515, lng: 113.390, d: "现代化市图书馆，少儿区与亲子自习空间大。", age: "0-16", free: true, io: "indoor", addr: "东区兴中道8号", tags: ["少儿区"] },
  { n: "中山影视城", c: "themepark", city: "中山", lat: 22.413, lng: 113.442, d: "民国主题影视基地，实景演出与服装体验。", age: "4-14", free: false, io: "both", addr: "南朗街道翠亨村", tags: ["民国", "演出"] },

  // ============ 惠州 ============
  { n: "惠州西湖风景区", c: "park", city: "惠州", lat: 23.095, lng: 114.400, d: "国家5A湖泊景区，免费开放，泗洲塔与九曲桥。", age: "0-14", free: true, io: "outdoor", addr: "惠城区环城西路", tags: ["5A"] },
  { n: "红花湖景区", c: "hiking", city: "惠州", lat: 23.072, lng: 114.378, d: "18公里环湖绿道，租自行车环湖是经典亲子项目。", age: "3-14", free: true, io: "outdoor", addr: "惠城区红花湖路", tags: ["骑行", "绿道"] },
  { n: "巽寮湾", c: "beach", city: "惠州", lat: 22.705, lng: 114.745, d: "惠东经典海湾，沙滩平缓，出海捕鱼体验多。", age: "0-14", free: true, io: "outdoor", addr: "惠东县巽寮镇", tags: ["沙滩", "出海"] },
  { n: "双月湾", c: "beach", city: "惠州", lat: 22.570, lng: 114.884, d: "两湾相连如双月，观景台看日出日落，海龟保护区在侧。", age: "2-14", free: true, io: "outdoor", addr: "惠东县港口镇", tags: ["观景台", "海龟"] },
  { n: "罗浮山风景区", c: "hiking", city: "惠州", lat: 23.275, lng: 114.053, d: "岭南第一山，索道上山，道教文化与飞瀑。", age: "4-16", free: false, io: "outdoor", addr: "博罗县长宁镇", tags: ["索道", "名山"] },
  { n: "南昆山生态旅游区", c: "camping", city: "惠州", lat: 23.634, lng: 113.853, d: "北回归线上的绿洲，竹林溪流，夏季避暑露营地多。", age: "3-14", free: false, io: "outdoor", addr: "龙门县南昆山", tags: ["避暑", "竹林"] },
  { n: "惠州科技馆", c: "museum", city: "惠州", lat: 23.088, lng: 114.418, d: "免费市级科技馆，基础科学互动展项。", age: "3-14", free: true, io: "indoor", addr: "惠城区江北文华一路", tags: ["互动"] },

  // ============ 江门 ============
  { n: "开平碉楼（自力村）", c: "museum", city: "江门", lat: 22.290, lng: 112.555, d: "世界文化遗产，中西合璧碉楼群，稻田风光。", age: "4-16", free: false, io: "outdoor", addr: "开平市塘口镇", tags: ["世遗", "碉楼"] },
  { n: "小鸟天堂", c: "hiking", city: "江门", lat: 22.512, lng: 113.075, d: "巴金笔下的独木成林，坐船观万鸟归巢。", age: "2-12", free: false, io: "outdoor", addr: "新会区会城街道", tags: ["观鸟", "游船"] },
  { n: "圭峰山国家森林公园", c: "hiking", city: "江门", lat: 22.610, lng: 113.055, d: "新会绿肺，玉台寺与登山步道，山脚绿道平缓。", age: "3-14", free: true, io: "outdoor", addr: "新会区圭峰路", tags: ["森林", "登山"] },
  { n: "古兜温泉小镇", c: "waterplay", city: "江门", lat: 22.210, lng: 112.935, d: "山海温泉度假区，夏有水世界冬泡温泉。", age: "2-14", free: false, io: "both", addr: "新会区崖门镇", tags: ["温泉", "水世界"] },
  { n: "五邑华侨华人博物馆", c: "museum", city: "江门", lat: 22.578, lng: 113.080, d: "华侨史主题博物馆，了解五邑侨乡故事。", age: "5-16", free: true, io: "indoor", addr: "蓬江区港口路", tags: ["华侨"] },
  { n: "上川岛飞沙滩", c: "beach", city: "江门", lat: 21.740, lng: 112.775, d: "广东知名海岛沙滩，需乘船上岛，水清沙幼。", age: "3-14", free: false, io: "outdoor", addr: "台山市川岛镇", tags: ["海岛", "沙滩"] },

  // ============ 肇庆 ============
  { n: "七星岩风景区", c: "park", city: "肇庆", lat: 23.060, lng: 112.460, d: "喀斯特湖岩景观，湖上石峰如北斗，游船环湖。", age: "2-14", free: false, io: "outdoor", addr: "端州区七星路", tags: ["喀斯特", "游船"] },
  { n: "鼎湖山风景区", c: "hiking", city: "肇庆", lat: 23.160, lng: 112.540, d: "北回归线绿宝石，负离子森林与蝴蝶谷飞水潭。", age: "3-14", free: false, io: "outdoor", addr: "鼎湖区上山路", tags: ["森林", "瀑布"] },
  { n: "肇庆牌坊公园", c: "park", city: "肇庆", lat: 23.047, lng: 112.465, d: "星湖旁市民广场，音乐喷泉夜晚开放。", age: "0-12", free: true, io: "outdoor", addr: "端州区天宁北路", tags: ["喷泉"] },
  { n: "紫云谷风景区", c: "waterplay", city: "肇庆", lat: 23.033, lng: 112.528, d: "西江畔溪谷景区，夏季天然山水泳池玩水胜地。", age: "3-14", free: false, io: "outdoor", addr: "端州区羚羊峡", tags: ["溪谷", "玩水"] },

  // ============ 深圳 · 商场亲子 ============
  { n: "深圳万象城", c: "mall", city: "深圳", lat: 22.520, lng: 114.107, d: "罗湖高端商场，童装旗舰与亲子餐厅集中，冰纷万象滑冰场常年开放。", age: "0-14", free: true, io: "indoor", addr: "罗湖区宝安南路1881号", tags: ["滑冰", "亲子餐厅"] },
  { n: "万象天地", c: "mall", city: "深圳", lat: 22.536, lng: 113.952, d: "南山开放式街区商场，Meland Club 旗舰店与户外艺术街区。", age: "0-14", free: true, io: "both", addr: "南山区深南大道9668号", tags: ["Meland", "街区"] },
  { n: "前海万象城", c: "mall", city: "深圳", lat: 22.532, lng: 113.903, d: "前海新地标商场，儿童绘本美育馆与骑乐马术室内体验中心。", age: "0-12", free: true, io: "indoor", addr: "前海桂湾片区", tags: ["马术", "绘本"] },
  { n: "深圳湾万象城", c: "mall", city: "深圳", lat: 22.506, lng: 113.937, d: "后海高端商场，儿童绘本馆与少儿艺术展览常设。", age: "0-12", free: true, io: "indoor", addr: "南山区科苑南路2888号", tags: ["艺术展", "绘本"] },
  { n: "益田假日广场", c: "mall", city: "深圳", lat: 22.539, lng: 113.972, d: "世界之窗旁一站式商场，室内滑冰场、卡丁车馆与汤姆熊电玩。", age: "2-14", free: true, io: "indoor", addr: "南山区深南大道9028号", tags: ["滑冰", "卡丁车"] },
  { n: "壹方城", c: "mall", city: "深圳", lat: 22.560, lng: 113.869, d: "宝安超大商场，Meland Club、茱莉动物园与运动娱乐业态齐全。", age: "0-14", free: true, io: "indoor", addr: "宝安区新湖路99号", tags: ["Meland", "室内动物园"] },
  { n: "中航城君尚购物中心", c: "mall", city: "深圳", lat: 22.543, lng: 114.086, d: "华强北商圈，双层乐高授权专卖店与 VR 体验矩阵。", age: "3-14", free: true, io: "indoor", addr: "福田区华强北路", tags: ["乐高", "VR"] },
  { n: "印力中心", c: "mall", city: "深圳", lat: 22.524, lng: 113.930, d: "南山家庭型商场，山姆会员店与反弹蹦床公园旗舰店。", age: "2-14", free: true, io: "indoor", addr: "南山区南海大道2748号", tags: ["蹦床", "山姆"] },
  { n: "福田星河COCO Park", c: "mall", city: "深圳", lat: 22.534, lng: 114.062, d: "福田CBD潮流商场，影城亲子厅与少儿电玩城。", age: "3-14", free: true, io: "indoor", addr: "福田区福华三路", tags: ["电影", "电玩"] },
  { n: "龙岗万达广场", c: "mall", city: "深圳", lat: 22.719, lng: 114.247, d: "龙岗中心城大商场，室内动物乐园、高空攀岩与马术中心。", age: "2-14", free: true, io: "indoor", addr: "龙岗区龙翔大道", tags: ["攀岩", "动物乐园"] },
  { n: "宝安大悦城", c: "mall", city: "深圳", lat: 22.566, lng: 113.884, d: "宝安新商场，亲子成长中心与新式室内游乐场集中。", age: "0-12", free: true, io: "indoor", addr: "宝安区新安街道", tags: ["室内乐园"] },
  { n: "华强广场", c: "mall", city: "深圳", lat: 22.546, lng: 114.088, d: "「熊出没」IP主题商场，熊熊食堂亲子餐厅与IP打卡场景。", age: "0-10", free: true, io: "indoor", addr: "福田区华强北路1019号", tags: ["熊出没", "IP"] },
  { n: "深业上城", c: "mall", city: "深圳", lat: 22.556, lng: 114.071, d: "笔架山旁彩色小镇商场，SONY科技体验馆与 Meland Club。", age: "2-14", free: true, io: "both", addr: "福田区皇岗路5001号", tags: ["科技", "彩色小镇"] },
  { n: "平安金融中心云际观光层", c: "mall", city: "深圳", lat: 22.537, lng: 114.050, d: "Free Sky 116层云端观光，数字化科普互动区俯瞰全城。", age: "4-16", free: false, io: "indoor", addr: "福田区益田路5033号", tags: ["观光", "地标"] },
  { n: "KK MALL", c: "mall", city: "深圳", lat: 22.541, lng: 114.108, d: "京基100旁商场，欧悦亲子滑冰俱乐部常年营业。", age: "3-14", free: true, io: "indoor", addr: "罗湖区深南东路5016号", tags: ["滑冰"] },
  { n: "龙华壹方天地", c: "mall", city: "深圳", lat: 22.616, lng: 114.026, d: "龙华超大商业体，Round 1 综合运动馆与 iFly 风洞飞行。", age: "3-16", free: true, io: "indoor", addr: "龙华区人民路", tags: ["风洞", "运动"] },
  { n: "招商花园城", c: "mall", city: "深圳", lat: 22.486, lng: 113.917, d: "蛇口社区型商场，小马快跑与金宝贝早教中心。", age: "0-6", free: true, io: "indoor", addr: "南山区蛇口南海大道", tags: ["早教"] },
  { n: "海雅缤纷城", c: "mall", city: "深圳", lat: 22.559, lng: 113.883, d: "宝安中心商场，欧悦真冰场与托马斯小镇主题乐园。", age: "2-12", free: true, io: "indoor", addr: "宝安区建安一路99号", tags: ["真冰场", "托马斯"] },
  { n: "欢乐海岸", c: "mall", city: "深圳", lat: 22.5285, lng: 113.9885, d: "滨海开放式商业区，水秀剧场演出与海洋奇梦馆。", age: "2-14", free: true, io: "both", addr: "南山区白石路东8号", tags: ["水秀", "海洋馆"] },

  // ============ 深圳 · 室内场馆 ============
  { n: "奈尔宝家庭中心（卓悦汇店）", c: "indoorplay", city: "深圳", lat: 22.567, lng: 114.046, d: "高端室内亲子乐园，仿真小镇角色扮演与图书馆区。", age: "1-10", free: false, io: "indoor", addr: "福田区梅林卓悦汇", tags: ["角色扮演", "网红"] },
  { n: "奈尔宝家庭中心（香蜜湖店）", c: "indoorplay", city: "深圳", lat: 22.540, lng: 114.033, d: "奈尔宝香蜜湖门店，滑梯球池与美食区一站式遛娃。", age: "1-10", free: false, io: "indoor", addr: "福田区深国投广场", tags: ["球池", "滑梯"] },
  { n: "Meland Club（深业上城店）", c: "indoorplay", city: "深圳", lat: 22.5565, lng: 114.0705, d: "超大高端室内乐园，星空主题球池与积木池。", age: "1-10", free: false, io: "indoor", addr: "福田区深业上城", tags: ["球池", "高颜值"] },
  { n: "Meland Club（壹方城店）", c: "indoorplay", city: "深圳", lat: 22.5605, lng: 113.8695, d: "宝安旗舰室内乐园，全场景主题游乐与托管服务。", age: "1-10", free: false, io: "indoor", addr: "宝安区壹方城", tags: ["旗舰店"] },
  { n: "海昌乐漫冰雪王国", c: "indoorplay", city: "深圳", lat: 22.573, lng: 113.882, d: "室内冰雪乐园，滑雪圈与冰滑梯，夏天避暑遛娃。", age: "3-12", free: false, io: "indoor", addr: "宝安区大仟里购物中心", tags: ["冰雪", "避暑"] },
  { n: "卡鲁冰雪世界", c: "indoorplay", city: "深圳", lat: 22.706, lng: 114.062, d: "观澜湖室内滑雪场，零基础滑雪课程与戏雪区。", age: "3-14", free: false, io: "indoor", addr: "龙华区观澜湖生态体育公园", tags: ["滑雪", "课程"] },
  { n: "反弹蹦床公园（红山店）", c: "indoorplay", city: "深圳", lat: 22.630, lng: 114.034, d: "大型室内蹦床公园，海绵池、攀岩墙与忍者闯关。", age: "4-16", free: false, io: "indoor", addr: "龙华区红山6979商业中心", tags: ["蹦床", "闯关"] },
  { n: "全明星滑冰俱乐部", c: "indoorplay", city: "深圳", lat: 22.5392, lng: 113.9723, d: "标准真冰场，少儿花样滑冰与冰球培训。", age: "4-16", free: false, io: "indoor", addr: "南山区益田假日广场", tags: ["真冰", "培训"] },
  { n: "木育森林（海上世界店）", c: "indoorplay", city: "深圳", lat: 22.485, lng: 113.916, d: "木质玩具主题亲子馆，上百种原木游具安静耐玩。", age: "1-8", free: false, io: "indoor", addr: "南山区海上世界", tags: ["木玩", "低龄"] },
  { n: "莫莉幻想（永旺丹竹头店）", c: "indoorplay", city: "深圳", lat: 22.597, lng: 114.118, d: "永旺系室内游乐园，转马与轨道小火车适合幼儿。", age: "1-8", free: false, io: "indoor", addr: "龙岗区永旺梦乐城", tags: ["幼儿", "亲民"] },
  { n: "星际传奇（卓悦中心店）", c: "indoorplay", city: "深圳", lat: 22.5375, lng: 114.0565, d: "大型电玩游艺中心，抓娃娃与体感游戏亲子同乐。", age: "4-16", free: false, io: "indoor", addr: "福田区卓悦中心", tags: ["电玩"] },

  // ============ 深圳 · 户外与场馆 ============
  { n: "锦绣中华·民俗文化村", c: "themepark", city: "深圳", lat: 22.5395, lng: 113.968, d: "微缩中国景观与民俗表演，节庆主题活动丰富。", age: "3-14", free: false, io: "outdoor", addr: "南山区深南大道9003号", tags: ["民俗", "演出"] },
  { n: "深圳青青世界", c: "farm", city: "深圳", lat: 22.507, lng: 113.909, d: "老牌生态园，热带雨林馆、陶艺与自然课堂。", age: "2-12", free: false, io: "outdoor", addr: "南山区月亮湾青青街1号", tags: ["生态", "陶艺"] },
  { n: "深圳红立方", c: "museum", city: "深圳", lat: 22.720, lng: 114.256, d: "龙岗科技馆+青少年宫+图书馆三馆合一，互动展项多。", age: "2-14", free: true, io: "indoor", addr: "龙岗区龙翔大道8035号", tags: ["科技馆", "三馆合一"] },
  { n: "深圳科学馆（福田馆）", c: "museum", city: "深圳", lat: 22.544, lng: 114.082, d: "老牌市科学馆，基础科学互动展项，票价亲民。", age: "3-12", free: false, io: "indoor", addr: "福田区上步中路1003号", tags: ["科普", "亲民"] },
  { n: "深圳当代艺术与城市规划馆", c: "museum", city: "深圳", lat: 22.5475, lng: 114.0635, d: "先锋建筑地标，当代艺术展与城市规划互动沙盘。", age: "4-16", free: true, io: "indoor", addr: "福田区莲花街道福中路184号", tags: ["艺术", "建筑"] },
  { n: "深圳市儿童公园", c: "playground", city: "深圳", lat: 22.561, lng: 114.121, d: "罗湖老牌儿童公园，摩天轮与户外游乐设施票价亲民。", age: "0-12", free: true, io: "outdoor", addr: "罗湖区童乐路12号", tags: ["摩天轮", "老牌"] },
  { n: "仙湖植物园", c: "park", city: "深圳", lat: 22.5755, lng: 114.1785, d: "梧桐山下山水植物园，古生物博物馆与湖区草坪。", age: "2-14", free: false, io: "outdoor", addr: "罗湖区仙湖路160号", tags: ["植物园", "古生物"] },
  { n: "小梅沙海洋世界", c: "zoo", city: "深圳", lat: 22.591, lng: 114.322, d: "全新重开的海洋馆，深海展缸与海洋剧场。", age: "1-14", free: false, io: "indoor", addr: "盐田区小梅沙", tags: ["海洋馆", "新馆"] },
  { n: "华侨城湿地公园", c: "hiking", city: "深圳", lat: 22.5315, lng: 113.9865, d: "城央湿地保护区，免费预约进入，自然学校观鸟研学。", age: "3-14", free: true, io: "outdoor", addr: "南山区白石路", tags: ["观鸟", "需预约"] },
  { n: "海上田园", c: "hiking", city: "深圳", lat: 22.7205, lng: 113.8035, d: "西部湿地生态园区，红树林基塘与农家体验。", age: "2-12", free: false, io: "outdoor", addr: "宝安区沙井民主大道", tags: ["湿地", "农事"] },
  { n: "观澜湖生态体育公园", c: "themepark", city: "深圳", lat: 22.703, lng: 114.064, d: "运动主题乐园，卡丁车、攀爬与手艺工场DIY。", age: "3-16", free: false, io: "both", addr: "龙华区观澜高尔夫大道", tags: ["运动", "手作"] },
  { n: "观澜山水田园", c: "farm", city: "深圳", lat: 22.737, lng: 114.055, d: "客家农庄度假区，摸鱼抓虾、采摘与小动物园。", age: "2-12", free: false, io: "outdoor", addr: "龙华区观澜街道", tags: ["农事", "抓鱼"], season: "全年" },
  { n: "大鹏所城", c: "museum", city: "深圳", lat: 22.5935, lng: 114.5165, d: "600年海防卫城，明清古建筑群亲子研学。", age: "4-16", free: true, io: "outdoor", addr: "大鹏新区鹏城社区", tags: ["古城", "研学"] },
  { n: "洪湖公园", c: "park", city: "深圳", lat: 22.5665, lng: 114.1175, d: "荷花主题市政公园，夏季赏荷与湿地科普。", age: "0-12", free: true, io: "outdoor", addr: "罗湖区文锦北路2023号", tags: ["荷花", "湿地"] },
  { n: "南山中山公园", c: "park", city: "深圳", lat: 22.5325, lng: 113.9195, d: "深圳最老公园之一，大型传统户外游乐场与草坪。", age: "0-12", free: true, io: "outdoor", addr: "南山区南山大道3109号", tags: ["游乐场", "老牌"] },
  { n: "深圳园博园", c: "park", city: "深圳", lat: 22.5405, lng: 113.9885, d: "多国微缩园林免费开放，登塔观景与亲子徒步。", age: "2-14", free: true, io: "outdoor", addr: "福田区深南大道8002号", tags: ["园林", "徒步"] },
  { n: "笔架山公园", c: "park", city: "深圳", lat: 22.5615, lng: 114.0725, d: "市中心山林公园，草坪野餐与登高望远。", age: "2-14", free: true, io: "outdoor", addr: "福田区梅岗路26号", tags: ["草坪", "登山"] },
  { n: "深圳中心公园", c: "park", city: "深圳", lat: 22.5445, lng: 114.0475, d: "城市绿带公园，露营草坪与飞盘活动聚集地。", age: "0-14", free: true, io: "outdoor", addr: "福田区振华西路", tags: ["露营", "飞盘"] },
  { n: "阳台山森林公园", c: "hiking", city: "深圳", lat: 22.649, lng: 113.955, d: "西部登高胜地，绿道成熟，山脚段适合亲子。", age: "5-16", free: true, io: "outdoor", addr: "宝安区石岩街道", tags: ["登山", "绿道"] },
  { n: "凤凰山森林公园", c: "hiking", city: "深圳", lat: 22.6855, lng: 113.8425, d: "宝安名山，凤凰古庙与登山步道，山脚广场开阔。", age: "4-16", free: true, io: "outdoor", addr: "宝安区福永凤凰村", tags: ["登山", "古庙"] },
  { n: "坪山儿童公园", c: "playground", city: "深圳", lat: 22.692, lng: 114.343, d: "山林主题无动力乐园，长滑梯与攀爬网免费玩。", age: "2-12", free: true, io: "outdoor", addr: "坪山区坪山街道", tags: ["无动力", "长滑梯"] },
  { n: "盐田中央公园", c: "playground", city: "深圳", lat: 22.5575, lng: 114.2365, d: "巨型大章鱼滑梯出圈，海滨儿童游乐场免费开放。", age: "2-12", free: true, io: "outdoor", addr: "盐田区深盐路", tags: ["章鱼滑梯", "网红"] },
  { n: "四海公园", c: "park", city: "深圳", lat: 22.4935, lng: 113.9225, d: "蛇口老牌社区公园，湖边步道与儿童游乐区。", age: "0-10", free: true, io: "outdoor", addr: "南山区工业四路", tags: ["社区", "湖景"] },
  { n: "南山博物馆", c: "museum", city: "深圳", lat: 22.5285, lng: 113.9305, d: "区级大馆，南山古代史与特展质量高，免费预约。", age: "4-16", free: true, io: "indoor", addr: "南山区南山大道2093号", tags: ["历史", "特展"] },
  { n: "宝安科技馆", c: "museum", city: "深圳", lat: 22.556, lng: 113.887, d: "区级科技馆，基础科学互动展与天文观测活动。", age: "3-14", free: true, io: "indoor", addr: "宝安区新安街道", tags: ["科普", "天文"] },
  { n: "大鹏半岛国家地质公园博物馆", c: "museum", city: "深圳", lat: 22.566, lng: 114.535, d: "火山地质科普馆，化石标本与地质步道研学。", age: "4-16", free: true, io: "both", addr: "大鹏新区新大社区", tags: ["地质", "化石"] },
  { n: "华强北博物馆", c: "museum", city: "深圳", lat: 22.5465, lng: 114.0865, d: "中国电子第一街主题馆，科技创新互动展。", age: "5-16", free: true, io: "indoor", addr: "福田区华强北路", tags: ["电子", "创新"] },
  { n: "坪山图书馆", c: "library", city: "深圳", lat: 22.6955, lng: 114.3475, d: "高颜值区级图书馆，少儿分馆与亲子阅读活动。", age: "0-16", free: true, io: "indoor", addr: "坪山区汇德路", tags: ["少儿馆"] },

  // ============ 广州 · 商场亲子 ============
  { n: "太古汇", c: "mall", city: "广州", lat: 23.133, lng: 113.3275, d: "天河高端商场，方所书店儿童绘本区与进口玩具专区。", age: "0-14", free: true, io: "indoor", addr: "天河区天河路383号", tags: ["方所", "绘本"] },
  { n: "天环广场", c: "mall", city: "广州", lat: 23.1325, lng: 113.3245, d: "双鲤鱼造型地标商场，乐高城市旗舰店与影城亲子厅。", age: "2-14", free: true, io: "both", addr: "天河区天河路218号", tags: ["乐高", "地标"] },
  { n: "天河城", c: "mall", city: "广州", lat: 23.1315, lng: 113.3195, d: "老牌一站式商场，天河城滑冰场与儿童百货娱乐层。", age: "2-14", free: true, io: "indoor", addr: "天河区天河路208号", tags: ["滑冰", "老牌"] },
  { n: "正佳广场", c: "mall", city: "广州", lat: 23.132, lng: 113.323, d: "亲子业态天花板：极地海洋世界、雨林生态园、自然科学博物馆全在一栋楼。", age: "1-14", free: true, io: "indoor", addr: "天河区天河路228号", tags: ["海洋馆", "博物馆"] },
  { n: "广州K11购物艺术中心", c: "mall", city: "广州", lat: 23.1195, lng: 113.3275, d: "艺术主题商场，儿童艺术工作坊与精品玩具店。", age: "2-12", free: true, io: "indoor", addr: "天河区珠江东路6号", tags: ["艺术", "工作坊"] },
  { n: "万博万达广场", c: "mall", city: "广州", lat: 22.999, lng: 113.334, d: "番禺万博商圈大商场，Meland Club 与万达宝贝王。", age: "1-12", free: true, io: "indoor", addr: "番禺区万博中心", tags: ["Meland", "宝贝王"] },
  { n: "太古仓码头", c: "park", city: "广州", lat: 23.0895, lng: 113.2455, d: "百年码头文创区，江畔市集与亲子观光游艇。", age: "2-14", free: true, io: "outdoor", addr: "海珠区革新路124号", tags: ["江景", "市集"] },
  { n: "东方宝泰购物广场", c: "mall", city: "广州", lat: 23.149, lng: 113.324, d: "广州东站地下商城，儿童卡丁车与潮玩专区。", age: "3-14", free: true, io: "indoor", addr: "天河区林和中路8号", tags: ["卡丁车"] },
  { n: "五号停机坪购物广场", c: "mall", city: "广州", lat: 23.158, lng: 113.262, d: "白云公园旁商场，星期8小镇职业体验与儿童天地。", age: "3-12", free: true, io: "indoor", addr: "白云区云城西路", tags: ["职业体验"] },
  { n: "悦汇城", c: "mall", city: "广州", lat: 23.083, lng: 113.232, d: "荔湾大型商场，奈尔宝家庭中心与乐漫冰雪王国。", age: "1-12", free: true, io: "indoor", addr: "荔湾区花地大道中", tags: ["奈尔宝", "冰雪"] },

  // ============ 广州 · 室内与乐园 ============
  { n: "广州热雪奇迹（融创雪世界）", c: "indoorplay", city: "广州", lat: 23.428, lng: 113.158, d: "华南最大室内滑雪场，戏雪区适合初次接触冰雪的孩子。", age: "3-16", free: false, io: "indoor", addr: "花都区融创文旅城", tags: ["滑雪", "戏雪"] },
  { n: "广州融创水世界", c: "waterplay", city: "广州", lat: 23.4285, lng: 113.161, d: "室内恒温水乐园，全年可玩，亲子戏水区丰富。", age: "2-14", free: false, io: "indoor", addr: "花都区融创文旅城", tags: ["恒温", "全年"] },
  { n: "广州塔", c: "themepark", city: "广州", lat: 23.1065, lng: 113.3245, d: "小蛮腰地标，高空摩天轮与观景层，夜景震撼。", age: "4-16", free: false, io: "indoor", addr: "海珠区阅江西路222号", tags: ["地标", "观景"] },
  { n: "广州大剧院", c: "museum", city: "广州", lat: 23.114, lng: 113.3175, d: "扎哈设计地标剧院，常年有少儿剧目与亲子演出。", age: "3-14", free: false, io: "indoor", addr: "天河区珠江西路1号", tags: ["演出", "亲子剧"] },
  { n: "广州市少年宫（珠江新城）", c: "museum", city: "广州", lat: 23.1195, lng: 113.322, d: "公益少年宫，兴趣课程与儿童剧场、展览活动。", age: "3-14", free: true, io: "indoor", addr: "天河区华就路273号", tags: ["兴趣班", "公益"] },

  // ============ 广州 · 户外与场馆 ============
  { n: "荔湾湖公园", c: "park", city: "广州", lat: 23.115, lng: 113.234, d: "西关水乡园林，泮塘古村相邻，龙船文化研学。", age: "0-12", free: true, io: "outdoor", addr: "荔湾区龙津西路", tags: ["水乡", "西关"] },
  { n: "流花湖公园", c: "park", city: "广州", lat: 23.140, lng: 113.252, d: "老广童年记忆，宝象乐园大白象滑梯经典打卡。", age: "0-12", free: true, io: "outdoor", addr: "越秀区流花路100号", tags: ["大白象", "湖景"] },
  { n: "麓湖公园", c: "park", city: "广州", lat: 23.157, lng: 113.281, d: "白云山南麓湖景公园，聚芳园草坪适合露营野餐。", age: "0-12", free: true, io: "outdoor", addr: "越秀区麓湖路", tags: ["露营", "草坪"] },
  { n: "海心沙亚运公园", c: "park", city: "广州", lat: 23.113, lng: 113.320, d: "珠江中心岛屿公园，广州塔对望，大草坪放风筝。", age: "0-12", free: true, io: "outdoor", addr: "天河区珠江中海心沙岛", tags: ["江景", "风筝"] },
  { n: "临江大道缓跑径公园", c: "park", city: "广州", lat: 23.1145, lng: 113.335, d: "珠江北岸带状公园，大型户外沙池与儿童游乐区。", age: "0-10", free: true, io: "outdoor", addr: "天河区临江大道", tags: ["沙池", "江景"] },
  { n: "珠江夜游（大沙头码头）", c: "park", city: "广州", lat: 23.113, lng: 113.287, d: "夜游珠江看两岸灯光，有亲子主题动漫游船班次。", age: "2-14", free: false, io: "outdoor", addr: "越秀区沿江东路466号", tags: ["游船", "夜景"] },
  { n: "神农草堂中医药博物馆", c: "museum", city: "广州", lat: 23.196, lng: 113.330, d: "半开放式中医药文化园，中草药辨识亲子研学。", age: "5-16", free: true, io: "both", addr: "白云区沙太北路389号", tags: ["中医药", "研学"] },
  { n: "岭南印象园", c: "museum", city: "广州", lat: 23.040, lng: 113.394, d: "岭南民俗文化园，非遗手工、皮影戏与传统街市。", age: "3-14", free: false, io: "both", addr: "番禺区大学城外环西路", tags: ["非遗", "民俗"] },
  { n: "宝墨园", c: "park", city: "广州", lat: 22.913, lng: 113.306, d: "番禺水乡园林，巨型锦鲤池投喂与岭南建筑。", age: "2-12", free: false, io: "outdoor", addr: "番禺区沙湾镇紫坭村", tags: ["锦鲤", "园林"] },
  { n: "南沙水鸟世界生态园", c: "zoo", city: "广州", lat: 22.622, lng: 113.622, d: "湿地鸟类主题园，近距离接触火烈鸟等珍稀水鸟。", age: "2-12", free: false, io: "outdoor", addr: "南沙区万顷沙镇", tags: ["水鸟", "投喂"] },
  { n: "天鹿湖森林公园", c: "hiking", city: "广州", lat: 23.205, lng: 113.437, d: "黄埔郊野绿肺，禾雀花季徒步胜地。", age: "4-14", free: true, io: "outdoor", addr: "黄埔区天鹿南路", tags: ["禾雀花", "徒步"] },
  { n: "帽峰山森林公园", c: "hiking", city: "广州", lat: 23.287, lng: 113.406, d: "广州市区最高峰，森林步道与溪流，避暑纳凉。", age: "5-16", free: true, io: "outdoor", addr: "白云区太和镇", tags: ["登山", "避暑"] },
  { n: "火炉山森林公园", c: "hiking", city: "广州", lat: 23.172, lng: 113.375, d: "天河后花园，缓坡土路适合亲子徒步与溯溪。", age: "4-14", free: true, io: "outdoor", addr: "天河区岑村", tags: ["徒步", "溯溪"] },
  { n: "聚龙古村", c: "museum", city: "广州", lat: 23.088, lng: 113.233, d: "保存完好的广府古村落，青砖大屋建筑研学。", age: "5-16", free: true, io: "outdoor", addr: "荔湾区冲口街道", tags: ["古村", "广府"] },
  { n: "沙面岛", c: "park", city: "广州", lat: 23.107, lng: 113.243, d: "欧式建筑露天博物馆，绿树浓荫适合漫步写生。", age: "2-14", free: true, io: "outdoor", addr: "荔湾区沙面", tags: ["建筑", "写生"] },
  { n: "中山纪念堂", c: "museum", city: "广州", lat: 23.133, lng: 113.262, d: "近代史地标建筑，木棉王古树与历史展览。", age: "5-16", free: false, io: "both", addr: "越秀区东风中路259号", tags: ["历史", "木棉"] },
  { n: "黄埔军校旧址纪念馆", c: "museum", city: "广州", lat: 23.079, lng: 113.528, d: "长洲岛近代史研学地标，免费预约参观。", age: "6-16", free: true, io: "both", addr: "黄埔区长洲岛军校路", tags: ["历史", "研学"] },
  { n: "辛亥革命纪念馆", c: "museum", city: "广州", lat: 23.083, lng: 113.525, d: "长洲岛历史纪念馆，与黄埔军校同线研学。", age: "6-16", free: true, io: "indoor", addr: "黄埔区长洲岛", tags: ["历史"] },
  { n: "碧水湾温泉度假村", c: "waterplay", city: "广州", lat: 23.667, lng: 113.740, d: "从化亲子温泉，儿童戏水区与恒温泡池。", age: "2-14", free: false, io: "both", addr: "从化区良口镇", tags: ["温泉", "度假"] },
  { n: "流溪河国家森林公园", c: "hiking", city: "广州", lat: 23.7385, lng: 113.7805, d: "从化湖光山色，游船观湖与森林徒步，冬赏梅花。", age: "3-14", free: false, io: "outdoor", addr: "从化区良口镇", tags: ["游船", "梅花"] },
  { n: "大夫山森林公园", c: "hiking", city: "广州", lat: 22.982, lng: 113.324, d: "番禺骑行天堂，亲子双人自行车环湖经典路线。", age: "3-14", free: true, io: "outdoor", addr: "番禺区市桥街道", tags: ["骑行", "环湖"] },
  { n: "番禺莲花山旅游区", c: "hiking", city: "广州", lat: 22.9485, lng: 113.4895, d: "古采石场奇观与莲花塔，夏季莲花节赏花。", age: "3-14", free: false, io: "outdoor", addr: "番禺区石楼镇", tags: ["采石场", "莲花"] },

  // ============ 香港 · 商场亲子 ============
  { n: "K11 MUSEA", c: "mall", city: "香港", lat: 22.2935, lng: 114.174, d: "维港文化商场，Donut Playhouse 巨型滑梯与自然探索公园，乐高探索中心也在此。", age: "1-12", free: true, io: "indoor", addr: "尖沙咀梳士巴利道18号", tags: ["乐高", "滑梯"] },
  { n: "海港城", c: "mall", city: "香港", lat: 22.2965, lng: 114.1685, d: "全港最大商场之一，玩具反斗城旗舰与海景餐厅街。", age: "0-14", free: true, io: "indoor", addr: "尖沙咀广东道3-27号", tags: ["玩具", "海景"] },
  { n: "时代广场", c: "mall", city: "香港", lat: 22.278, lng: 114.182, d: "铜锣湾地标商场，高层儿童服饰与益智玩具专区。", age: "0-12", free: true, io: "indoor", addr: "铜锣湾勿地臣街1号", tags: ["购物"] },
  { n: "IFC商场", c: "mall", city: "香港", lat: 22.285, lng: 114.158, d: "中环海滨商场，连卡佛儿童精品与空中花园。", age: "0-12", free: true, io: "indoor", addr: "中环金融街8号", tags: ["空中花园"] },
  { n: "圆方 Elements", c: "mall", city: "香港", lat: 22.3045, lng: 114.1615, d: "九龙站上盖商场，The Rink 溜冰场亲子友好。", age: "3-14", free: true, io: "indoor", addr: "西九龙柯士甸道西1号", tags: ["溜冰"] },
  { n: "太古广场", c: "mall", city: "香港", lat: 22.2775, lng: 114.1655, d: "金钟高端商场，亲子概念影院与精品童装。", age: "2-14", free: true, io: "indoor", addr: "金钟道88号", tags: ["影院"] },
  { n: "又一城", c: "mall", city: "香港", lat: 22.337, lng: 114.175, d: "九龙塘商场，欢天雪地真冰溜冰场全港知名。", age: "3-14", free: true, io: "indoor", addr: "九龙塘达之路80号", tags: ["溜冰", "真冰"] },
  { n: "围方 THE WAI", c: "mall", city: "香港", lat: 22.373, lng: 114.179, d: "大围新商场，多功能亲子影院与室内娱乐空间。", age: "2-12", free: true, io: "indoor", addr: "大围车公庙路18号", tags: ["新商场"] },
  { n: "启德 AIRSIDE", c: "mall", city: "香港", lat: 22.3305, lng: 114.1975, d: "启德新地标，室内冲浪中心与儿童数码娱乐馆。", age: "4-16", free: true, io: "indoor", addr: "启德协调道2号", tags: ["冲浪", "数码"] },
  { n: "愉景新城 D·PARK", c: "mall", city: "香港", lat: 22.3755, lng: 114.1105, d: "荃湾亲子主题商场，多元智能儿童游乐设施免费区多。", age: "0-10", free: true, io: "indoor", addr: "荃湾青山公路398号", tags: ["亲子商场"] },
  { n: "沙田新城市广场", c: "mall", city: "香港", lat: 22.3815, lng: 114.188, d: "史诺比开心世界户外乐园免费开放，Kiztopia 室内乐园也在此。", age: "1-12", free: true, io: "both", addr: "沙田正街18号", tags: ["史诺比", "免费乐园"] },
  { n: "V Walk", c: "mall", city: "香港", lat: 22.3265, lng: 114.1595, d: "南昌站上盖商场，室内大型充气城堡游乐场。", age: "1-10", free: true, io: "indoor", addr: "深水埗深旺道28号", tags: ["充气城堡"] },
  { n: "朗豪坊", c: "mall", city: "香港", lat: 22.318, lng: 114.1695, d: "旺角地标商场，乐高认证专卖店有香港特色巨型模型。", age: "3-14", free: true, io: "indoor", addr: "旺角亚皆老街8号", tags: ["乐高"] },
  { n: "MOKO 新世纪广场", c: "mall", city: "香港", lat: 22.322, lng: 114.173, d: "旺角东商场，MOKO 动乐园室外巨型攀爬网。", age: "3-12", free: true, io: "both", addr: "旺角太子道西193号", tags: ["攀爬网"] },
  { n: "荃湾广场", c: "mall", city: "香港", lat: 22.3695, lng: 114.1115, d: "荃湾海滨商场，空中彩虹主题无动力乐园。", age: "2-10", free: true, io: "both", addr: "荃湾大坝街4-30号", tags: ["无动力", "天台"] },

  // ============ 香港 · 室内场馆 ============
  { n: "Kiztopia（沙田店）", c: "indoorplay", city: "香港", lat: 22.3818, lng: 114.1878, d: "新加坡品牌室内亲子乐园，主题闯关与角色扮演。", age: "1-10", free: false, io: "indoor", addr: "沙田新城市广场", tags: ["闯关", "角色扮演"] },
  { n: "Verm City 攀岩乐园", c: "indoorplay", city: "香港", lat: 22.2875, lng: 114.2095, d: "室内巨型攀岩馆，儿童攀爬区与忍者障碍赛道。", age: "4-16", free: false, io: "indoor", addr: "鲗鱼涌华兰路20号", tags: ["攀岩", "忍者"] },
  { n: "Epicland 历奇王国", c: "indoorplay", city: "香港", lat: 22.295, lng: 114.016, d: "愉景湾巨型室内游乐场，彩虹滑梯与蹦床区。", age: "1-12", free: false, io: "indoor", addr: "愉景湾广场", tags: ["彩虹滑梯"] },
  { n: "Sooper Yoo", c: "indoorplay", city: "香港", lat: 22.286, lng: 114.135, d: "科技主题室内乐园，数码互动与体能挑战结合。", age: "2-12", free: false, io: "indoor", addr: "石塘咀西宝城", tags: ["科技", "互动"] },

  // ============ 香港 · 户外与场馆 ============
  { n: "香港故宫文化博物馆", c: "museum", city: "香港", lat: 22.3015, lng: 114.156, d: "西九文化区新馆，故宫珍藏与少儿文创工作坊。", age: "5-16", free: false, io: "indoor", addr: "西九文化区博物馆道8号", tags: ["故宫", "工作坊"] },
  { n: "西九文化区艺术公园", c: "park", city: "香港", lat: 22.304, lng: 114.158, d: "维港海滨大草坪，租单车、野餐看日落的亲子胜地。", age: "0-14", free: true, io: "outdoor", addr: "西九龙文化区", tags: ["草坪", "单车"] },
  { n: "香港海防博物馆", c: "museum", city: "香港", lat: 22.2815, lng: 114.236, d: "百年炮台堡垒改建，户外军事遗迹步道研学。", age: "5-16", free: true, io: "both", addr: "筲箕湾东喜道175号", tags: ["堡垒", "免费"] },
  { n: "香港铁路博物馆", c: "museum", city: "香港", lat: 22.4445, lng: 114.167, d: "大埔旧火车站改建，复古火车车厢实景可登乘。", age: "2-12", free: true, io: "both", addr: "大埔墟崇德街13号", tags: ["火车", "免费"] },
  { n: "太平山顶", c: "hiking", city: "香港", lat: 22.2712, lng: 114.150, d: "山顶缆车登顶看维港，山顶广场有儿童游乐区与大富翁梦想世界。", age: "3-16", free: false, io: "both", addr: "港岛太平山", tags: ["缆车", "夜景"] },
  { n: "大澳渔村", c: "hiking", city: "香港", lat: 22.2535, lng: 113.8605, d: "水上棚屋渔村，出海观中华白海豚科普线路。", age: "3-14", free: true, io: "outdoor", addr: "大屿山大澳", tags: ["白海豚", "渔村"] },
  { n: "中环海滨活动空间", c: "park", city: "香港", lat: 22.2855, lng: 114.1615, d: "维港海滨大空地，季节性亲子嘉年华与摩天轮。", age: "2-14", free: true, io: "outdoor", addr: "中环龙和道9号", tags: ["嘉年华", "摩天轮"] },
  { n: "尖沙咀海滨长廊", c: "park", city: "香港", lat: 22.293, lng: 114.172, d: "星光大道维港景观步道，傍晚看幻彩咏香江。", age: "0-14", free: true, io: "outdoor", addr: "尖沙咀梳士巴利道", tags: ["维港", "夜景"] },

  // ============ 澳门 · 度假村与场馆 ============
  { n: "威尼斯人 Q立方王国", c: "indoorplay", city: "澳门", lat: 22.1455, lng: 113.5645, d: "度假村内儿童地带，攀爬太空网与主题滑梯。", age: "1-10", free: false, io: "indoor", addr: "路氹金光大道威尼斯人", tags: ["攀爬", "度假村"] },
  { n: "澳门巴黎人水世界", c: "waterplay", city: "澳门", lat: 22.1415, lng: 113.5645, d: "巴黎铁塔下的室内外水上乐园与电玩区。", age: "2-14", free: false, io: "both", addr: "路氹金光大道巴黎人", tags: ["水乐园", "铁塔"] },
  { n: "新濠影汇", c: "themepark", city: "澳门", lat: 22.140, lng: 113.560, d: "影汇之星8字摩天轮、满纷乐园室内游乐场与室内外滑索。", age: "3-16", free: false, io: "both", addr: "路氹连贯公路新濠影汇", tags: ["摩天轮", "滑索"] },
  { n: "澳门伦敦人", c: "mall", city: "澳门", lat: 22.1435, lng: 113.5625, d: "英伦主题度假村，沉浸式展览与大本钟建筑打卡。", age: "3-14", free: true, io: "indoor", addr: "路氹金光大道伦敦人", tags: ["英伦", "展览"] },
  { n: "美狮美高梅视博广场", c: "mall", city: "澳门", lat: 22.1495, lng: 113.5665, d: "巨型室内数字艺术天幕广场，光影景观免费观赏。", age: "2-14", free: true, io: "indoor", addr: "路氹体育馆大马路", tags: ["光影", "免费"] },
  { n: "澳门银河天浪淘园", c: "waterplay", city: "澳门", lat: 22.1515, lng: 113.5605, d: "全球最长空中激流与人造白沙滩冲浪池（住客专享为主）。", age: "2-14", free: false, io: "outdoor", addr: "路氹望德圣母湾大马路", tags: ["冲浪", "白沙滩"] },
  { n: "澳门大赛车博物馆", c: "museum", city: "澳门", lat: 22.1995, lng: 113.5515, d: "格兰披治赛车主题馆，赛车模拟器少儿可玩。", age: "4-16", free: false, io: "indoor", addr: "高美士街431号", tags: ["赛车", "模拟器"] },
  { n: "大三巴牌坊", c: "museum", city: "澳门", lat: 22.1975, lng: 113.541, d: "澳门地标世遗，历史城区研学步道起点。", age: "3-16", free: true, io: "outdoor", addr: "大三巴巷", tags: ["世遗", "地标"] },
  { n: "澳门博物馆", c: "museum", city: "澳门", lat: 22.1975, lng: 113.5435, d: "大炮台山顶博物馆，澳门四百年历史全景展。", age: "4-16", free: false, io: "indoor", addr: "澳门博物馆前地112号", tags: ["历史", "炮台"] },
  { n: "观音像海滨休憩区", c: "playground", city: "澳门", lat: 22.186, lng: 113.553, d: "澳门最大户外儿童游乐场，分龄设施免费开放。", age: "0-12", free: true, io: "outdoor", addr: "孙逸仙大马路", tags: ["免费", "海滨"] },
  { n: "童梦天地", c: "indoorplay", city: "澳门", lat: 22.1485, lng: 113.562, d: "新濠天地高端室内亲子乐园，益智竞技与创意工坊。", age: "1-10", free: false, io: "indoor", addr: "路氹连贯公路新濠天地", tags: ["益智", "工坊"] },

  // ============ 珠海 / 佛山 / 东莞 / 中山 / 江门 补充 ============
  { n: "珠海大剧院（日月贝）", c: "park", city: "珠海", lat: 22.2805, lng: 113.5945, d: "野狸岛海上贝壳剧院，环岛步道与亲子艺术演出。", age: "2-14", free: true, io: "both", addr: "香洲区野狸岛", tags: ["地标", "海岛"] },
  { n: "美的鹭湖森林度假区", c: "hiking", city: "佛山", lat: 22.800, lng: 112.749, d: "高明度假区，白鹭湖观鸟、安纳希小镇与亲子徒步。", age: "2-14", free: false, io: "outdoor", addr: "高明区杨和镇", tags: ["观鸟", "小镇"] },
  { n: "佛山祖庙", c: "museum", city: "佛山", lat: 23.029, lng: 113.107, d: "岭南圣域，醒狮表演与武术文化非遗研学。", age: "4-16", free: false, io: "both", addr: "禅城区祖庙路21号", tags: ["醒狮", "非遗"] },
  { n: "岭南天地", c: "mall", city: "佛山", lat: 23.031, lng: 113.109, d: "历史建筑活化街区，少儿书店与非遗手作坊。", age: "2-14", free: true, io: "both", addr: "禅城区祖庙大街", tags: ["街区", "手作"] },
  { n: "佛山科学馆", c: "museum", city: "佛山", lat: 23.006, lng: 113.145, d: "佛山新城科学馆，生命科学与数码科技互动展。", age: "3-14", free: true, io: "indoor", addr: "顺德区乐从镇", tags: ["科普", "互动"] },
  { n: "东莞龙凤山庄影视度假村", c: "themepark", city: "东莞", lat: 22.744, lng: 114.134, d: "欧式影视城，儿童嘉年华游乐场与花海。", age: "2-12", free: false, io: "outdoor", addr: "凤岗镇官井头", tags: ["嘉年华", "花海"] },
  { n: "鸦片战争博物馆（林则徐纪念馆）", c: "museum", city: "东莞", lat: 22.821, lng: 113.663, d: "虎门销烟池旧址，近代史实景研学基地。", age: "5-16", free: true, io: "both", addr: "虎门镇解放路113号", tags: ["历史", "免费"] },
  { n: "中山长江水世界", c: "waterplay", city: "中山", lat: 22.521, lng: 113.433, d: "深海主题水上乐园，大喇叭滑道与亲子戏水区。", age: "3-14", free: false, io: "outdoor", addr: "东区长江旅游区", tags: ["水乐园", "滑道"] },
  { n: "中山红博城", c: "museum", city: "中山", lat: 22.4735, lng: 113.3195, d: "红木文化博览城，木雕非遗少儿手作体验。", age: "4-14", free: true, io: "indoor", addr: "大涌镇岐涌路", tags: ["红木", "手作"] },
  { n: "江门启明里", c: "museum", city: "江门", lat: 22.579, lng: 113.083, d: "百年侨乡历史街区，文创小店与非遗手工体验。", age: "3-14", free: true, io: "outdoor", addr: "蓬江区启明里", tags: ["侨乡", "街区"] },
  { n: "古劳水乡", c: "park", city: "江门", lat: 22.7745, lng: 112.9615, d: "岭南威尼斯水乡，童梦村泥巴乐园与水上无动力设施。", age: "2-12", free: false, io: "outdoor", addr: "鹤山市古劳镇", tags: ["水乡", "玩泥巴"] },
];
