/**
 * 英文翻译（键: "城市|中文名"，与 js/data.js 对应）。缺失自动回退中文。
 * 由人工翻译维护；如新增地点，按同样格式补一条即可。
 */
const ACTIVITIES_EN = {
  // ===== 深圳 Shenzhen =====
  "深圳|深圳湾公园": { n: "Shenzhen Bay Park", d: "Seaside promenade for cycling, kite-flying and watching migratory birds, with wide-open sea views." },
  "深圳|莲花山公园": { n: "Lianhuashan Park", d: "Big downtown lawn and a kite plaza; the hilltop overlooks the Civic Center." },
  "深圳|香蜜公园": { n: "Xiangmi Park", d: "Elevated boardwalks, lychee groves and a kids' play zone; flower fields by the wedding hall are great for photos." },
  "深圳|人才公园": { n: "Talent Park", d: "Lakeside loop and evening lights right by Shenzhen Bay — lovely for a dusk stroll with kids." },
  "深圳|福田红树林生态公园": { n: "Futian Mangrove Eco Park", d: "Mangrove wetland with boardwalks and birdwatching; best in the winter migratory season." },
  "深圳|深圳市儿童乐园": { n: "Shenzhen Children's Amusement Park", d: "Non-profit kids' park with a Ferris wheel and rides at friendly prices." },
  "深圳|深圳欢乐港湾": { n: "Shenzhen OH Bay", d: "Bay Glow Ferris wheel, seaside lawns and a large outdoor children's playground." },
  "深圳|深圳图书馆": { n: "Shenzhen Library", d: "Landmark central library with a rich kids' collection and weekend family events." },
  "深圳|深圳少年儿童图书馆": { n: "Shenzhen Children's Library", d: "Library built just for kids, with a picture-book area and frequent storytime events." },
  "深圳|深圳博物馆（历史民俗馆）": { n: "Shenzhen Museum (History & Folk Culture)", d: "Free city museum on Shenzhen's reform history and folk customs, with weekend kids' tours." },
  "深圳|深圳野生动物园": { n: "Shenzhen Safari Park", d: "Open-range zoo where you can see giraffes and flamingos up close, plus animal shows." },
  "深圳|深圳欢乐谷": { n: "Shenzhen Happy Valley", d: "Large theme park with roller coasters and a kids' zone; night sessions in summer." },
  "深圳|世界之窗": { n: "Window of the World", d: "Miniatures of world landmarks, with big evening shows and fireworks." },
  "深圳|东部华侨城": { n: "OCT East", d: "Mountain theme resort (Tea Stream Valley + Knight Valley) with cable cars and a mountain mini-train." },
  "深圳|大梅沙海滨公园": { n: "Dameisha Beach Park", d: "Free city beach with mature facilities; booking required in peak season." },
  "深圳|较场尾海滩": { n: "Jiaochangwei Beach", d: "Dapeng guesthouse beach village with fine sand — great for an overnight family getaway." },
  "深圳|西涌沙滩": { n: "Xichong Beach", d: "Shenzhen's longest beach; a dark-sky community for stargazing, with clear water and few crowds." },
  "深圳|梧桐山国家级风景区": { n: "Wutong Mountain Scenic Area", d: "Shenzhen's highest peak, good for older kids; the Xiutong route is gentler." },
  "深圳|塘朗山郊野公园": { n: "Tanglang Mountain Country Park", d: "Gentle country greenway with Shenzhen Bay views from the top — a beginner family hike." },
  "深圳|马峦山郊野公园": { n: "Maluan Mountain Country Park", d: "One of Shenzhen's rare waterfall-and-valley hikes; you can play in the water in summer." },
  "深圳|光明农场大观园": { n: "Guangming Farm", d: "Dairy demonstration farm with milking, small-animal feeding and grass sledding." },
  "深圳|甘坑古镇": { n: "Gankeng Old Town", d: "Hakka old town with a kids' hat-themed area and photogenic historic buildings." },
  "深圳|杨梅坑": { n: "Yangmeikeng", d: "Seaside cycling greenway and the Luzui trail where mountains meet the sea." },
  "深圳|深圳海上世界": { n: "Shenzhen Sea World", d: "Minghua ship plaza with a musical fountain and seaside dining — great for evening outings." },

  // ===== 广州 Guangzhou =====
  "广州|长隆野生动物世界": { n: "Chimelong Safari Park", d: "One of Asia's top zoos with koalas and pandas; a mini-train crosses the drive-through zone." },
  "广州|长隆欢乐世界": { n: "Chimelong Paradise", d: "Big amusement park famous for its vertical coaster, with a well-equipped kids' zone." },
  "广州|长隆水上乐园": { n: "Chimelong Water Park", d: "One of the world's busiest water parks, with rich family splash zones." },
  "广州|广州动物园": { n: "Guangzhou Zoo", d: "Long-established downtown zoo with friendly prices, reachable by metro." },
  "广州|正佳极地海洋世界": { n: "Grandview Aquarium", d: "In-mall aquarium with belugas and penguins — a great rainy-day pick." },
  "广州|广州图书馆": { n: "Guangzhou Library", d: "Landmark library on Flower City Square with a huge kids' wing; booking required." },
  "广州|广州少年儿童图书馆": { n: "Guangzhou Children's Library", d: "Dedicated children's library with age-based reading zones and regular storytime." },
  "广州|广东省博物馆": { n: "Guangdong Museum", d: "The 'treasure box' provincial museum; kids love the dinosaur fossils and ocean hall." },
  "广州|广东科学中心": { n: "Guangdong Science Center", d: "One of Asia's largest science museums, packed with hands-on exhibits — an all-day visit." },
  "广州|越秀公园": { n: "Yuexiu Park", d: "Century-old park with the Five Rams statue, lakes, hills and big lawns." },
  "广州|天河公园": { n: "Tianhe Park", d: "Large free downtown park; lakeside lawns are perfect for picnics and tents." },
  "广州|海珠湖公园": { n: "Haizhu Lake Park", d: "City green heart by Canton Tower; the flat lakeside loop suits strollers." },
  "广州|海珠国家湿地公园": { n: "Haizhu National Wetland Park", d: "Central-city wetland with orchards and a birdwatching tower, rich in nature classes." },
  "广州|白云山风景区": { n: "Baiyun Mountain", d: "Guangzhou's iconic peak; family-friendly cable car up and an open summit plaza." },
  "广州|华南国家植物园": { n: "South China Botanical Garden", d: "National botanical garden with greenhouses and a bromeliad garden; year-round nature classes." },
  "广州|广州市儿童公园": { n: "Guangzhou Children's Park", d: "Large free kids' park with sandpits, water-play and age-based play equipment." },
  "广州|二沙岛艺术公园": { n: "Ersha Island Art Park", d: "Quiet island in the Pearl River with big lawns and sculptures — great for picnics and cycling." },
  "广州|广州融创乐园": { n: "Guangzhou Sunac Land", d: "Big Huadu theme park, with an indoor ski slope and water world too." },
  "广州|石门国家森林公园": { n: "Shimen National Forest Park", d: "A natural oxygen bar in Conghua — flowers in spring, red leaves in autumn, and stream trails." },
  "广州|白水寨风景名胜区": { n: "Baishuizhai Scenic Area", d: "One of the mainland's tallest waterfalls, with a 9,999-step trail you can take at your own pace." },
  "广州|南沙湿地公园": { n: "Nansha Wetland Park", d: "A migratory-bird haven in the Pearl River Delta; tour the wetland by boat, best in winter." },
  "广州|从化溪头村": { n: "Xitou Village, Conghua", d: "Longevity-village hikes and seasonal fruit picking — plums in summer, sugar oranges in winter." },

  // ===== 香港 Hong Kong =====
  "香港|香港迪士尼乐园": { n: "Hong Kong Disneyland", d: "Asia's classic Disney park; the Frozen land is a hit, with a fireworks finale." },
  "香港|香港海洋公园": { n: "Ocean Park Hong Kong", d: "Mountain-and-sea theme park with a giant panda house and aquarium; the cable car crossing is stunning." },
  "香港|海洋公园水上乐园": { n: "Water World, Ocean Park", d: "All-weather seaside water park with indoor and outdoor slides open year-round." },
  "香港|香港科学馆": { n: "Hong Kong Science Museum", d: "Hands-on science museum famous for its energy machine; the Children's Gallery suits toddlers." },
  "香港|香港太空馆": { n: "Hong Kong Space Museum", d: "Egg-shaped planetarium — don't miss the dome-screen films in the Space Theatre." },
  "香港|香港历史博物馆": { n: "Hong Kong Museum of History", d: "The Hong Kong Story exhibit recreates old Hong Kong streets in full scale." },
  "香港|M+ 博物馆": { n: "M+ Museum", d: "Contemporary visual-culture museum in the West Kowloon Cultural District; picnic on the harbour lawn." },
  "香港|香港湿地公园": { n: "Hong Kong Wetland Park", d: "Tin Shui Wai wetland reserve with bird hides and a mangrove boardwalk — very educational." },
  "香港|香港中央图书馆": { n: "Hong Kong Central Library", d: "The city's largest public library; the toy library needs booking." },
  "香港|九龙公园": { n: "Kowloon Park", d: "A green oasis in the city with a flamingo pond and a large children's playground." },
  "香港|香港公园": { n: "Hong Kong Park", d: "Central hillside park with a free walk-through aviary." },
  "香港|维多利亚公园": { n: "Victoria Park", d: "Hong Kong Island's biggest park with playgrounds and lawns; lively flower markets at festivals." },
  "香港|浅水湾泳滩": { n: "Repulse Bay Beach", d: "Classic Island beach with fine sand and gentle waves, well-equipped." },
  "香港|石澳泳滩": { n: "Shek O Beach", d: "Small-village beach in the southeast Island; colorful houses make great photos." },
  "香港|清水湾二滩": { n: "Clearwater Bay Second Beach", d: "Clean, pretty Sai Kung beach popular with families on weekends." },
  "香港|昂坪360与大佛": { n: "Ngong Ping 360 & Big Buddha", d: "Crystal cable car over Lantau, plus the Tian Tan Buddha and Ngong Ping village market." },
  "香港|龙脊远足径": { n: "Dragon's Back Trail", d: "One of Asia's best urban hikes — a ridge line with sea views, good for older kids." },
  "香港|塔门岛": { n: "Grass Island (Tap Mun)", d: "Big-lawn island camping spot with cows, sea and stargazing; reached by boat." },
  "香港|嘉道理农场暨植物园": { n: "Kadoorie Farm & Botanic Garden", d: "Hillside eco farm with an animal rescue center and organic fields — a model for nature education." },
  "香港|挪亚方舟主题公园": { n: "Noah's Ark", d: "Life-size ark on Ma Wan with hands-on family galleries and outdoor climbing." },
  "香港|香港动植物公园": { n: "Hong Kong Zoological & Botanical Gardens", d: "Free century-old gardens in Central with orangutans and lemurs." },

  // ===== 澳门 Macau =====
  "澳门|澳门科学馆": { n: "Macao Science Center", d: "I.M. Pei-designed waterfront science center with clearly age-based interactive halls." },
  "澳门|石排湾郊野公园与大熊猫馆": { n: "Seac Pai Van Park & Giant Panda Pavilion", d: "Country park at the foot of Coloane with an affordable panda pavilion and an animal zone." },
  "澳门|黑沙海滩": { n: "Hac Sa Beach", d: "Macau's largest natural beach with distinctive black sand and a BBQ area nearby." },
  "澳门|龙环葡韵": { n: "Taipa Houses (Casas-Museu)", d: "Five mint-green Portuguese villas by a wetland; the museums are free and egrets abound." },
  "澳门|氹仔中央公园": { n: "Taipa Central Park", d: "Large park in residential Taipa with a fresh, modern children's playground." },
  "澳门|二龙喉公园与松山缆车": { n: "Flora Garden & Guia Cable Car", d: "Ride the world's shortest cable car up Guia Hill to its lighthouse and fortress." },
  "澳门|澳门海事博物馆": { n: "Macao Maritime Museum", d: "Maritime history museum by A-Ma Temple with ship models and interactive exhibits." },
  "澳门|teamLab 超自然空间": { n: "teamLab SuperNature Macao", d: "Immersive digital-art space by The Venetian; the light-and-shadow interactions mesmerize kids." },

  // ===== 珠海 Zhuhai =====
  "珠海|珠海长隆海洋王国": { n: "Chimelong Ocean Kingdom", d: "World-class ocean theme park with a whale-shark tank and a fireworks show." },
  "珠海|长隆宇宙飞船": { n: "Chimelong Spaceship", d: "Huge spaceship-shaped indoor ocean-science park — top pick for rainy days." },
  "珠海|珠海渔女与情侣路": { n: "Fisher Girl Statue & Lovers' Road", d: "Zhuhai's landmark statue; the coastal path suits strollers and scooters." },
  "珠海|珠海海滨公园": { n: "Zhuhai Seaside Park", d: "Classic free seaside park with big lawns and a kids' play area." },
  "珠海|珠海博物馆": { n: "Zhuhai Museum", d: "New waterfront museum on Zhuhai's history and ocean culture; free with booking." },
  "珠海|淇澳岛红树林保护区": { n: "Qi'ao Island Mangrove Reserve", d: "Mangrove boardwalks and a fishing village; family-friendly island cycling." },
  "珠海|板樟山健身步道": { n: "Banzhang Mountain Fitness Trail", d: "Forest ridge trail with viewing decks overlooking both Zhuhai and Macau." },
  "珠海|香山湖公园": { n: "Xiangshan Lake Park", d: "New park where hills meet water, with a lakeside greenway and big lawns." },
  "珠海|东澳岛": { n: "Dong'ao Island", d: "Resort island in the Wanshan archipelago; Nansha Bay has clear water — reached by boat." },
  "珠海|外伶仃岛": { n: "Wailingding Island", d: "Sea-view outer island; the Shijingshan trail looks toward Hong Kong, and the seafood is famous." },
  "珠海|珠海图书馆": { n: "Zhuhai Library", d: "City library with a spacious kids' area and many weekend talks and events." },

  // ===== 佛山 Foshan =====
  "佛山|千灯湖公园": { n: "Qiandeng Lake Park", d: "Central waterfront park in Nanhai with an evening light show and open lawns." },
  "佛山|佛山市图书馆": { n: "Foshan Library", d: "Large library in Foshan New City with a dedicated kids' activity space." },
  "佛山|南风古灶": { n: "Nanfeng Ancient Kiln", d: "A 500-year-old living dragon kiln with hands-on pottery wheel-throwing for families." },
  "佛山|西樵山风景区": { n: "Xiqiao Mountain", d: "Famous Lingnan mountain with Guanyin culture and lake trails, reachable by cable car." },
  "佛山|长鹿旅游休博园": { n: "Changlu Amusement Resort", d: "Long-established Shunde family park: zoo + rides + farm experiences." },
  "佛山|顺德欢乐海岸PLUS": { n: "Shunde OCT Harbour PLUS", d: "Waterfront park and Maya water park with a pretty Ferris-wheel night view." },
  "佛山|亚洲艺术公园": { n: "Asian Art Park", d: "Chancheng waterfront park with bridges, waterscapes and broad lawns." },
  "佛山|三水荷花世界": { n: "Sanshui Lotus World", d: "Summer lotus-viewing park — a lovely spot for family sketching in lotus season." },
  "佛山|盈香生态园": { n: "Yingxiang Eco Park", d: "All-round Gaoming eco park with seasonal flower seas, U-pick and rides." },
  "佛山|美的鹭湖水世界": { n: "Midea Egret Lake Water World", d: "Water park in the Gaoming resort, with an adventure kingdom and hot springs too." },

  // ===== 东莞 Dongguan =====
  "东莞|松山湖景区": { n: "Songshan Lake", d: "A cycling paradise around the lake; the golden trumpet trees go viral each spring." },
  "东莞|东莞植物园": { n: "Dongguan Botanical Garden", d: "Large free botanical garden with themed gardens and big picnic lawns." },
  "东莞|东莞市科学技术博物馆": { n: "Dongguan Science & Technology Museum", d: "Manufacturing-themed science museum with distinctive robotics exhibits." },
  "东莞|海战博物馆": { n: "Sea Battle Museum", d: "History of the opium destruction and the Opium War; stroll the seaside fort ruins." },
  "东莞|银瓶山森林公园": { n: "Yinping Mountain Forest Park", d: "Dongguan's highest peak; the first stretch of the valley trail is gentle and family-friendly." },
  "东莞|隐贤山庄": { n: "Yinxian Villa", d: "All-round Changping park with rides and animal encounters at great value." },
  "东莞|华阳湖国家湿地公园": { n: "Huayang Lake National Wetland Park", d: "Machong water-town wetland with greenway cycling and sunset boat rides." },
  "东莞|东莞图书馆": { n: "Dongguan Library", d: "A pioneer of 24-hour self-service libraries, with a rich picture-book collection." },
  "东莞|香市动物园": { n: "Xiangshi Zoo", d: "Mid-sized Liaobu zoo with animal shows and feeding at friendly prices." },

  // ===== 中山 Zhongshan =====
  "中山|中山詹园": { n: "Zhongshan Zhan Garden", d: "The largest private garden in Lingnan, with classical architecture and filial-piety culture." },
  "中山|孙中山故里旅游区": { n: "Dr. Sun Yat-sen's Hometown", d: "Former residence and memorial in Cuiheng Village — a history and humanities study route." },
  "中山|金钟湖公园": { n: "Jinzhong Lake Park", d: "Lakeside loop and a children's playground — Zhongshan's back garden." },
  "中山|紫马岭公园": { n: "Zimaling Park", d: "Classic municipal park with a bird garden and wide green space." },
  "中山|中山纪念图书馆": { n: "Zhongshan Memorial Library", d: "Modern city library with a big kids' area and family study space." },
  "中山|中山影视城": { n: "Zhongshan Film & TV City", d: "Republic-era film base with live shows and costume experiences." },

  // ===== 惠州 Huizhou =====
  "惠州|惠州西湖风景区": { n: "Huizhou West Lake", d: "National 5A lake scenic area, free to enter, with Sizhou Pagoda and a nine-bend bridge." },
  "惠州|红花湖景区": { n: "Honghua Lake", d: "An 18 km lakeside greenway; renting bikes to loop the lake is a classic family outing." },
  "惠州|巽寮湾": { n: "Xunliao Bay", d: "Classic Huidong bay with a gentle beach and lots of fishing-trip experiences." },
  "惠州|双月湾": { n: "Shuangyue Bay", d: "Two bays joined like a double moon; watch sunrise and sunset from the lookout, next to a sea-turtle reserve." },
  "惠州|罗浮山风景区": { n: "Luofu Mountain", d: "The 'first mountain of Lingnan' with a ropeway, Taoist culture and cascading falls." },
  "惠州|南昆山生态旅游区": { n: "Nankun Mountain Eco Area", d: "An oasis on the Tropic of Cancer with bamboo and streams; many summer camping spots." },
  "惠州|惠州科技馆": { n: "Huizhou Science Museum", d: "Free city science museum with basic hands-on science exhibits." },

  // ===== 江门 Jiangmen =====
  "江门|开平碉楼（自力村）": { n: "Kaiping Diaolou (Zili Village)", d: "World Heritage watchtowers blending Chinese and Western styles, amid rice-field scenery." },
  "江门|小鸟天堂": { n: "Bird Paradise", d: "The 'single tree that became a forest' of Ba Jin's essay; take a boat to see thousands of birds return." },
  "江门|圭峰山国家森林公园": { n: "Guifeng Mountain Forest Park", d: "Xinhui's green lung with Yutai Temple and hiking trails; the foothill greenway is flat." },
  "江门|古兜温泉小镇": { n: "Gudou Hot Spring Town", d: "Mountain-and-sea hot-spring resort — a water world in summer, hot springs in winter." },
  "江门|五邑华侨华人博物馆": { n: "Wuyi Overseas Chinese Museum", d: "Museum on overseas-Chinese history — learn the stories of the Wuyi diaspora." },
  "江门|上川岛飞沙滩": { n: "Feisha Beach, Shangchuan Island", d: "A well-known Guangdong island beach with clear water and fine sand; reached by boat." },

  // ===== 肇庆 Zhaoqing =====
  "肇庆|七星岩风景区": { n: "Seven Star Crags", d: "Karst lake-and-crag scenery; stone peaks rise from the lake like the Big Dipper — tour by boat." },
  "肇庆|鼎湖山风景区": { n: "Dinghu Mountain", d: "A 'green gem' on the Tropic of Cancer, with negative-ion forest and the Butterfly Valley falls." },
  "肇庆|肇庆牌坊公园": { n: "Zhaoqing Paifang Park", d: "Civic plaza by Star Lake with a musical fountain that opens in the evening." },
  "肇庆|紫云谷风景区": { n: "Ziyun Valley", d: "Stream valley by the Xijiang River — a great summer spot for natural mountain-water pools." },

  // ===== 深圳 · 商场亲子 Shenzhen malls =====
  "深圳|深圳万象城": { n: "MixC Shenzhen", d: "Upscale Luohu mall packed with kids' fashion flagships and family restaurants; the ice rink is open year-round." },
  "深圳|万象天地": { n: "MixC World", d: "Open-air block mall in Nanshan with a Meland Club flagship and an outdoor art block." },
  "深圳|前海万象城": { n: "Qianhai MixC", d: "New Qianhai landmark mall with a kids' picture-book art center and an indoor horse-riding center." },
  "深圳|深圳湾万象城": { n: "Shenzhen Bay MixC", d: "Upscale Houhai mall with a permanent kids' picture-book hall and children's art exhibitions." },
  "深圳|益田假日广场": { n: "Yitian Holiday Plaza", d: "One-stop mall by Window of the World, with an indoor ice rink, go-karts and a Tom's World arcade." },
  "深圳|壹方城": { n: "One Avenue Mall", d: "Huge Bao'an mall with Meland Club, an indoor zoo and full sports-entertainment options." },
  "深圳|中航城君尚购物中心": { n: "AVIC Junshang Shopping Center", d: "In the Huaqiangbei area, with a two-story licensed LEGO store and a VR experience matrix." },
  "深圳|印力中心": { n: "InCity Center", d: "Family-oriented Nanshan mall with a Sam's Club and a Reebound trampoline park flagship." },
  "深圳|福田星河COCO Park": { n: "Futian Galaxy COCO Park", d: "Trendy CBD mall with a family cinema hall and a kids' arcade." },
  "深圳|龙岗万达广场": { n: "Longgang Wanda Plaza", d: "Big mall in Longgang center with an indoor animal park, high-ropes climbing and a riding center." },
  "深圳|宝安大悦城": { n: "Bao'an Joy City", d: "New Bao'an mall clustered with family growth centers and modern indoor playgrounds." },
  "深圳|华强广场": { n: "Huaqiang Plaza", d: "Boonie Bears IP-themed mall with a themed family restaurant and IP photo spots." },
  "深圳|深业上城": { n: "Shum Yip UpperHills", d: "Colorful 'town' mall by Bijia Hill with a SONY tech gallery and a Meland Club." },
  "深圳|平安金融中心云际观光层": { n: "Ping An Finance Center Free Sky", d: "116th-floor Free Sky observation deck with a digital science zone overlooking the whole city." },
  "深圳|KK MALL": { n: "KK MALL", d: "Mall by KingKey 100 with a Ole family ice-skating club open year-round." },
  "深圳|龙华壹方天地": { n: "Longhua One Mall", d: "Huge Longhua complex with a Round 1 sports arcade and an iFly indoor skydiving wind tunnel." },
  "深圳|招商花园城": { n: "Merchants Garden City", d: "Community mall in Shekou with Pony Run and Gymboree early-learning centers." },
  "深圳|海雅缤纷城": { n: "Haiya Binfen City", d: "Bao'an-center mall with a real Ole ice rink and a Thomas Town theme park." },
  "深圳|欢乐海岸": { n: "OCT Harbour", d: "Open-air waterfront district with a water-show theatre and an ocean fantasy hall." },

  // ===== 深圳 · 室内场馆 Shenzhen indoor =====
  "深圳|奈尔宝家庭中心（卓悦汇店）": { n: "Nubo Family Center (Uniwalk)", d: "Upscale indoor family park with a mock-town role-play area and a library zone." },
  "深圳|奈尔宝家庭中心（香蜜湖店）": { n: "Nubo Family Center (Xiangmi Lake)", d: "Nubo's Xiangmi Lake branch with slides, ball pits and a dining zone — one-stop play." },
  "深圳|Meland Club（深业上城店）": { n: "Meland Club (UpperHills)", d: "Huge upscale indoor park with a starry-themed ball pit and a block pit." },
  "深圳|Meland Club（壹方城店）": { n: "Meland Club (One Avenue)", d: "Flagship Bao'an indoor park with full themed play and childcare service." },
  "深圳|海昌乐漫冰雪王国": { n: "Haichang Snow & Ice Kingdom", d: "Indoor snow-and-ice park with snow tubing and ice slides — a cool summer escape." },
  "深圳|卡鲁冰雪世界": { n: "Karu Snow World", d: "Indoor ski slope at Mission Hills with beginner lessons and a snow-play zone." },
  "深圳|反弹蹦床公园（红山店）": { n: "Reebound Trampoline Park (Hongshan)", d: "Large indoor trampoline park with foam pits, a climbing wall and a ninja course." },
  "深圳|全明星滑冰俱乐部": { n: "All Star Skating Club", d: "Standard real-ice rink with kids' figure-skating and ice-hockey training." },
  "深圳|木育森林（海上世界店）": { n: "Wooderful Life (Sea World)", d: "Wooden-toy-themed family venue with hundreds of quiet, durable wooden toys." },
  "深圳|莫莉幻想（永旺丹竹头店）": { n: "Molly Fantasy (AEON Danzhutou)", d: "AEON indoor play park; carousels and track trains suit toddlers." },
  "深圳|星际传奇（卓悦中心店）": { n: "Star Legend Arcade (One Avenue)", d: "Large arcade with claw machines and motion games for the whole family." },

  // ===== 深圳 · 户外与场馆 Shenzhen outdoor/venues =====
  "深圳|锦绣中华·民俗文化村": { n: "Splendid China & Folk Culture Village", d: "Miniature China landscapes and folk performances, rich with festival events." },
  "深圳|深圳青青世界": { n: "Shenzhen Qingqing World", d: "Long-standing eco park with a rainforest hall, pottery and nature classes." },
  "深圳|深圳红立方": { n: "Shenzhen Red Cube", d: "Longgang's 3-in-1 science museum, youth palace and library, with many hands-on exhibits." },
  "深圳|深圳科学馆（福田馆）": { n: "Shenzhen Science Museum (Futian)", d: "Long-established city science museum with basic hands-on exhibits at friendly prices." },
  "深圳|深圳当代艺术与城市规划馆": { n: "Museum of Contemporary Art & Urban Planning", d: "Avant-garde architecture landmark with contemporary art and an interactive city-planning model." },
  "深圳|深圳市儿童公园": { n: "Shenzhen Children's Park (Luohu)", d: "Long-standing Luohu kids' park with a Ferris wheel and outdoor play at friendly prices." },
  "深圳|仙湖植物园": { n: "Fairy Lake Botanical Garden", d: "Landscape botanical garden below Wutong Mountain with a paleontology museum and lakeside lawns." },
  "深圳|小梅沙海洋世界": { n: "Xiaomeisha Sea World", d: "Newly reopened aquarium with deep-sea tanks and an ocean theatre." },
  "深圳|华侨城湿地公园": { n: "OCT Wetland Park", d: "Central-city wetland reserve; free with booking, with a nature school and birdwatching study." },
  "深圳|海上田园": { n: "Ocean Paradise (Haishang Tianyuan)", d: "Western wetland eco park with mangrove ponds and farm experiences." },
  "深圳|观澜湖生态体育公园": { n: "Mission Hills Eco Sports Park", d: "Sports-themed park with go-karts, climbing and craft-workshop DIY." },
  "深圳|观澜山水田园": { n: "Guanlan Countryside Resort", d: "Hakka farm resort with fish-catching, U-pick and a petting zoo." },
  "深圳|大鹏所城": { n: "Dapeng Fortress", d: "A 600-year coastal defense fort; a family study tour among Ming–Qing buildings." },
  "深圳|洪湖公园": { n: "Honghu Park", d: "Lotus-themed municipal park with summer lotus viewing and wetland science." },
  "深圳|南山中山公园": { n: "Nanshan Zhongshan Park", d: "One of Shenzhen's oldest parks, with a large traditional outdoor playground and lawns." },
  "深圳|深圳园博园": { n: "Shenzhen International Garden Expo Park", d: "Free miniature gardens from many countries; climb the tower and hike with kids." },
  "深圳|笔架山公园": { n: "Bijiashan Park", d: "Downtown wooded park for lawn picnics and climbing up for a view." },
  "深圳|深圳中心公园": { n: "Shenzhen Central Park", d: "City green-belt park and a gathering spot for camping lawns and frisbee." },
  "深圳|阳台山森林公园": { n: "Yangtaishan Forest Park", d: "Western hiking spot with a mature greenway; the foothill section suits families." },
  "深圳|凤凰山森林公园": { n: "Fenghuangshan Forest Park", d: "A famous Bao'an mountain with the old Phoenix Temple, hiking trails and an open foothill plaza." },
  "深圳|坪山儿童公园": { n: "Pingshan Children's Park", d: "Forest-themed no-power play park with long slides and climbing nets, free to play." },
  "深圳|盐田中央公园": { n: "Yantian Central Park", d: "Its giant octopus slide went viral; the seaside kids' playground is free." },
  "深圳|四海公园": { n: "Sihai Park", d: "Long-standing Shekou community park with lakeside paths and a kids' play area." },
  "深圳|南山博物馆": { n: "Nanshan Museum", d: "Large district museum with strong Nanshan-history and special exhibits; free with booking." },
  "深圳|宝安科技馆": { n: "Bao'an Science Museum", d: "District science museum with basic hands-on exhibits and astronomy events." },
  "深圳|大鹏半岛国家地质公园博物馆": { n: "Dapeng Peninsula Geopark Museum", d: "Volcanic-geology museum with fossil specimens and a geology-trail study tour." },
  "深圳|华强北博物馆": { n: "Huaqiangbei Museum", d: "Museum of 'China's No.1 Electronics Street' with interactive tech-innovation displays." },
  "深圳|坪山图书馆": { n: "Pingshan Library", d: "Good-looking district library with a kids' branch and family reading events." },

  // ===== 广州 · 商场 Guangzhou malls =====
  "广州|太古汇": { n: "Taikoo Hui", d: "Upscale Tianhe mall with a Fangsuo Books kids' picture-book area and imported-toy zone." },
  "广州|天环广场": { n: "Parc Central", d: "Twin-carp landmark mall with a LEGO City flagship and a family cinema hall." },
  "广州|天河城": { n: "Teemall", d: "Classic one-stop mall with an ice rink and a kids' department & entertainment floor." },
  "广州|正佳广场": { n: "Grandview Mall", d: "The peak of family formats: aquarium, rainforest eco garden and natural-science museum, all in one building." },
  "广州|广州K11购物艺术中心": { n: "Guangzhou K11 Art Mall", d: "Art-themed mall with kids' art workshops and a boutique toy store." },
  "广州|万博万达广场": { n: "Wanbo Wanda Plaza", d: "Big Panyu Wanbo mall with Meland Club and Wanda Kids." },
  "广州|太古仓码头": { n: "Taikoo Cang Wharf", d: "Century-old wharf culture district with a riverside market and family sightseeing yachts." },
  "广州|东方宝泰购物广场": { n: "Teem Plaza", d: "Underground mall at Guangzhou East Station with kids' go-karts and a trendy-toy zone." },
  "广州|五号停机坪购物广场": { n: "Apron No.5 Plaza", d: "Mall by Baiyun Park with Kids' City job role-play and a children's zone." },
  "广州|悦汇城": { n: "Joy City Guangzhou", d: "Large Liwan mall with a Nubo Family Center and a snow-and-ice kingdom." },

  // ===== 广州 · 室内与乐园 Guangzhou indoor =====
  "广州|广州热雪奇迹（融创雪世界）": { n: "Sunac Snow Park Guangzhou", d: "South China's largest indoor ski slope, with a snow-play zone for kids' first taste of snow." },
  "广州|广州融创水世界": { n: "Sunac Water World Guangzhou", d: "Indoor heated water park, playable year-round with rich family splash zones." },
  "广州|广州塔": { n: "Canton Tower", d: "The 'slim waist' landmark with a sky Ferris wheel and observation decks — stunning at night." },
  "广州|广州大剧院": { n: "Guangzhou Opera House", d: "Zaha-designed landmark theatre with year-round kids' plays and family shows." },
  "广州|广州市少年宫（珠江新城）": { n: "Guangzhou Children's Palace (Zhujiang New Town)", d: "Non-profit children's palace with interest classes, a kids' theatre and exhibitions." },

  // ===== 广州 · 户外与场馆 Guangzhou outdoor/venues =====
  "广州|荔湾湖公园": { n: "Liwan Lake Park", d: "Xiguan water-town garden next to the old Pantang village — a dragon-boat culture study tour." },
  "广州|流花湖公园": { n: "Liuhua Lake Park", d: "A Guangzhou childhood memory; the classic white-elephant slide at Baoxiang playground is a must-snap." },
  "广州|麓湖公园": { n: "Luhu Park", d: "Lake park at the south foot of Baiyun Mountain; the Jufang lawn is great for camping and picnics." },
  "广州|海心沙亚运公园": { n: "Haixinsha Asian Games Park", d: "Island park in the Pearl River facing Canton Tower — fly kites on the big lawn." },
  "广州|临江大道缓跑径公园": { n: "Linjiang Avenue Riverside Park", d: "Ribbon park on the north bank of the Pearl River with a big outdoor sandpit and kids' play area." },
  "广州|珠江夜游（大沙头码头）": { n: "Pearl River Night Cruise (Dashatou Pier)", d: "Cruise the Pearl River by night to see both banks lit up; family cartoon-themed sailings available." },
  "广州|神农草堂中医药博物馆": { n: "Shennong Herb TCM Museum", d: "Semi-open TCM culture garden with a herb-identification study tour for families." },
  "广州|岭南印象园": { n: "Lingnan Impression Park", d: "Lingnan folk-culture park with heritage crafts, shadow puppetry and a traditional street market." },
  "广州|宝墨园": { n: "Baomo Garden", d: "Panyu water-town garden with a giant koi pond to feed and Lingnan architecture." },
  "广州|南沙水鸟世界生态园": { n: "Nansha Waterbird World", d: "Wetland bird-themed park where you can meet flamingos and other rare waterbirds up close." },
  "广州|天鹿湖森林公园": { n: "Tianluhu Forest Park", d: "Huangpu's country green lung — a hiking spot in Bauhinia-bloom season." },
  "广州|帽峰山森林公园": { n: "Maofeng Mountain Forest Park", d: "Guangzhou's highest urban peak with forest trails and streams — cool in summer." },
  "广州|火炉山森林公园": { n: "Huolushan Forest Park", d: "Tianhe's back garden; gentle dirt trails suit family hiking and stream trekking." },
  "广州|聚龙古村": { n: "Julong Old Village", d: "Well-preserved Cantonese old village — a study tour of grey-brick mansions." },
  "广州|沙面岛": { n: "Shamian Island", d: "Open-air museum of European architecture; shady trees make it great for strolls and sketching." },
  "广州|中山纪念堂": { n: "Sun Yat-sen Memorial Hall", d: "Modern-history landmark building with the ancient kapok 'king' tree and history exhibits." },
  "广州|黄埔军校旧址纪念馆": { n: "Whampoa Military Academy Memorial", d: "A modern-history study landmark on Changzhou Island; free with booking." },
  "广州|辛亥革命纪念馆": { n: "1911 Revolution Museum", d: "History museum on Changzhou Island, on the same study route as the Whampoa Academy." },
  "广州|碧水湾温泉度假村": { n: "Bishuiwan Hot Spring Resort", d: "Family hot springs in Conghua with a kids' splash zone and heated pools." },
  "广州|流溪河国家森林公园": { n: "Liuxihe National Forest Park", d: "Conghua's lakes and mountains; boat tours and forest hikes, with plum blossoms in winter." },
  "广州|大夫山森林公园": { n: "Dafushan Forest Park", d: "A Panyu cycling paradise; looping the lake on a family tandem bike is the classic route." },
  "广州|番禺莲花山旅游区": { n: "Panyu Lotus Hill", d: "Ancient-quarry wonders and the Lotus Pagoda, with a summer lotus festival." },

  // ===== 香港 · 商场 Hong Kong malls =====
  "香港|K11 MUSEA": { n: "K11 MUSEA", d: "Harbourfront culture mall with the Donut Playhouse giant slide, Nature Discovery Park and a LEGO Discovery Centre." },
  "香港|海港城": { n: "Harbour City", d: "One of Hong Kong's largest malls with a Toys\"R\"Us flagship and a harbour-view dining street." },
  "香港|时代广场": { n: "Times Square", d: "Causeway Bay landmark mall with upper-floor kids' fashion and educational-toy zones." },
  "香港|IFC商场": { n: "IFC Mall", d: "Central harbourfront mall with a Lane Crawford kids' boutique and a sky garden." },
  "香港|圆方 Elements": { n: "Elements", d: "Mall atop Kowloon Station with the family-friendly The Rink ice rink." },
  "香港|太古广场": { n: "Pacific Place", d: "Upscale Admiralty mall with a family-concept cinema and boutique kidswear." },
  "香港|又一城": { n: "Festival Walk", d: "Kowloon Tong mall famous city-wide for its Glacier real-ice skating rink." },
  "香港|围方 THE WAI": { n: "THE WAI", d: "New Tai Wai mall with a multi-function family cinema and indoor entertainment space." },
  "香港|启德 AIRSIDE": { n: "AIRSIDE", d: "New Kai Tak landmark with an indoor surfing center and a kids' digital-entertainment hall." },
  "香港|愉景新城 D·PARK": { n: "D·PARK", d: "Family-themed Tsuen Wan mall with lots of free multiple-intelligence play facilities." },
  "香港|沙田新城市广场": { n: "New Town Plaza", d: "Snoopy's World outdoor park is free to enter, and Kiztopia indoor park is here too." },
  "香港|V Walk": { n: "V Walk", d: "Mall atop Nam Cheong Station with a large indoor bouncy-castle playground." },
  "香港|朗豪坊": { n: "Langham Place", d: "Mong Kok landmark mall with a certified LEGO store featuring giant Hong Kong models." },
  "香港|MOKO 新世纪广场": { n: "MOKO", d: "Mong Kok East mall with MOKO's outdoor giant climbing net." },
  "香港|荃湾广场": { n: "Tsuen Wan Plaza", d: "Tsuen Wan harbourfront mall with a rooftop rainbow-themed no-power playground." },

  // ===== 香港 · 室内场馆 Hong Kong indoor =====
  "香港|Kiztopia（沙田店）": { n: "Kiztopia (Sha Tin)", d: "Singapore-brand indoor family park with themed obstacle courses and role-play." },
  "香港|Verm City 攀岩乐园": { n: "Verm City", d: "Indoor giant climbing gym with a kids' climbing zone and a ninja obstacle course." },
  "香港|Epicland 历奇王国": { n: "Epicland", d: "Giant indoor playground in Discovery Bay with rainbow slides and a trampoline zone." },
  "香港|Sooper Yoo": { n: "Sooper Yoo", d: "Tech-themed indoor park combining digital interaction with physical challenges." },

  // ===== 香港 · 户外与场馆 Hong Kong outdoor/venues =====
  "香港|香港故宫文化博物馆": { n: "Hong Kong Palace Museum", d: "New museum in the West Kowloon Cultural District with Palace treasures and kids' creative workshops." },
  "香港|西九文化区艺术公园": { n: "West Kowloon Art Park", d: "Big harbourfront lawn — a family favorite for renting bikes, picnicking and watching the sunset." },
  "香港|香港海防博物馆": { n: "Hong Kong Museum of Coastal Defence", d: "Converted century-old fort with an outdoor military-relics trail study tour." },
  "香港|香港铁路博物馆": { n: "Hong Kong Railway Museum", d: "Converted old Tai Po station where you can board vintage train carriages." },
  "香港|太平山顶": { n: "Victoria Peak", d: "Ride the Peak Tram up for harbour views; the Peak has a kids' play area and Monopoly Dreams." },
  "香港|大澳渔村": { n: "Tai O Fishing Village", d: "Stilt-house fishing village with a boat trip to spot Chinese white dolphins." },
  "香港|中环海滨活动空间": { n: "Central Harbourfront Event Space", d: "Big harbourfront open space with seasonal family carnivals and a Ferris wheel." },
  "香港|尖沙咀海滨长廊": { n: "Tsim Sha Tsui Promenade", d: "Avenue of Stars harbour walk — watch the Symphony of Lights at dusk." },

  // ===== 澳门 · 度假村与场馆 Macau resorts/venues =====
  "澳门|威尼斯人 Q立方王国": { n: "The Venetian – Qube Kingdom", d: "In-resort kids' zone with a space-net climb and themed slides." },
  "澳门|澳门巴黎人水世界": { n: "The Parisian Aqua World", d: "Indoor-outdoor water park and arcade beneath the Eiffel Tower replica." },
  "澳门|新濠影汇": { n: "Studio City", d: "Golden Reel figure-8 Ferris wheel, Super Fun Zone indoor playground and indoor-outdoor zipline." },
  "澳门|澳门伦敦人": { n: "The Londoner Macao", d: "British-themed resort with immersive exhibitions and Big Ben photo spots." },
  "澳门|美狮美高梅视博广场": { n: "MGM Cotai Spectacle", d: "Giant indoor digital-art atrium; the light-and-shadow scenery is free to view." },
  "澳门|澳门银河天浪淘园": { n: "Galaxy Grand Resort Deck", d: "The world's longest sky-top rapids and an artificial white-sand surf beach (mainly for guests)." },
  "澳门|澳门大赛车博物馆": { n: "Macau Grand Prix Museum", d: "Grand Prix racing museum with racing simulators kids can play." },
  "澳门|大三巴牌坊": { n: "Ruins of St. Paul's", d: "Macau's landmark World Heritage site — the start of the Historic Centre study walk." },
  "澳门|澳门博物馆": { n: "Macao Museum", d: "Museum atop Mount Fortress with a panoramic view of Macau's 400-year history." },
  "澳门|观音像海滨休憩区": { n: "Kun Iam Statue Waterfront", d: "Macau's largest outdoor children's playground with free age-based facilities." },
  "澳门|童梦天地": { n: "Kids' Cavern (City of Dreams)", d: "Upscale indoor family park at City of Dreams with brain games and creative workshops." },

  // ===== 珠海/佛山/东莞/中山/江门 补充 add-ons =====
  "珠海|珠海大剧院（日月贝）": { n: "Zhuhai Opera House (Sun & Moon Shells)", d: "Seaside shell-shaped opera house on Yeli Island, with an island loop trail and family art shows." },
  "佛山|美的鹭湖森林度假区": { n: "Midea Egret Lake Forest Resort", d: "Gaoming resort with egret-lake birdwatching, Annecy Town and family hiking." },
  "佛山|佛山祖庙": { n: "Foshan Ancestral Temple", d: "A Lingnan holy site with lion-dance shows and a martial-arts heritage study tour." },
  "佛山|岭南天地": { n: "Lingnan Tiandi", d: "Revitalized historic-building block with a kids' bookstore and heritage-craft workshops." },
  "佛山|佛山科学馆": { n: "Foshan Science Museum", d: "Science museum in Foshan New City with life-science and digital-tech interactive exhibits." },
  "东莞|东莞龙凤山庄影视度假村": { n: "Longfeng Villa Film Resort", d: "European-style film town with a kids' carnival playground and flower seas." },
  "东莞|鸦片战争博物馆（林则徐纪念馆）": { n: "Opium War Museum (Lin Zexu Memorial)", d: "On the site of the Humen opium destruction — a modern-history study base." },
  "中山|中山长江水世界": { n: "Zhongshan Changjiang Water World", d: "Deep-sea-themed water park with a big tornado slide and family splash zones." },
  "中山|中山红博城": { n: "Zhongshan Redwood Expo City", d: "Rosewood-culture expo city with kids' wood-carving heritage-craft experiences." },
  "江门|江门启明里": { n: "Jiangmen Qiming Li", d: "Century-old overseas-Chinese historic block with creative shops and heritage-craft experiences." },
  "江门|古劳水乡": { n: "Gulao Water Town", d: "The 'Venice of Lingnan' with the Tongmeng Village mud playground and no-power water play." },
};
