/**
 * 大湾区亲子活动数据
 * 坐标为近似位置（WGS-84），详情页提供地图导航链接以名称搜索为准。
 * 字段: n=名称, c=分类, city=城市, lat/lng=坐标, d=简介,
 *       age=适合年龄, free=是否免费, io=室内/户外(indoor/outdoor/both),
 *       addr=地址, tags=标签, season=采摘季节(仅农场)
 */
const ACTIVITIES = [
  // ============ 深圳 ============
  { n: "深圳湾公园", c: "park", city: "深圳", lat: 22.517, lng: 113.947, d: "滨海长廊，适合骑行、放风筝、看候鸟，海景开阔。", age: "0-14", free: true, io: "outdoor", addr: "南山区滨海大道", tags: ["海景", "骑行", "观鸟"] },
  { n: "莲花山公园", c: "park", city: "深圳", lat: 22.551, lng: 114.060, d: "市中心大草坪与风筝广场，山顶可俯瞰市民中心。", age: "0-14", free: true, io: "outdoor", addr: "福田区红荔路6030号", tags: ["草坪", "风筝"] },
  { n: "香蜜公园", c: "park", city: "深圳", lat: 22.552, lng: 114.026, d: "空中栈道、荔枝林与儿童游乐区，婚礼堂旁花田好拍照。", age: "0-12", free: true, io: "outdoor", addr: "福田区农园路30号", tags: ["栈道", "花田"] },
  { n: "人才公园", c: "park", city: "深圳", lat: 22.518, lng: 113.935, d: "环湖步道与夜景灯光，紧邻深圳湾，适合傍晚遛娃。", age: "0-14", free: true, io: "outdoor", addr: "南山区科苑南路", tags: ["湖景", "夜景"] },
  { n: "福田红树林生态公园", c: "hiking", city: "深圳", lat: 22.524, lng: 114.005, d: "红树林湿地科普，栈道观鸟，冬季候鸟季最佳。", age: "3-14", free: true, io: "outdoor", addr: "福田区新洲路南端", tags: ["湿地", "观鸟", "科普"] },
  { n: "深圳市儿童乐园", c: "playground", city: "深圳", lat: 22.554, lng: 114.023, d: "公益性儿童乐园，摩天轮与多种机动游戏，票价亲民。", age: "2-12", free: false, io: "outdoor", addr: "福田区侨香路", tags: ["机动游戏", "摩天轮"] },
  { n: "深圳欢乐港湾", c: "playground", city: "深圳", lat: 22.535, lng: 113.891, d: "湾区之光摩天轮、滨海草坪与大型户外儿童乐园。", age: "0-14", free: true, io: "outdoor", addr: "宝安区海天路", tags: ["摩天轮", "滨海"] },
  { n: "深圳图书馆", c: "library", city: "深圳", lat: 22.547, lng: 114.056, d: "市中心地标图书馆，少儿馆藏丰富，周末有亲子活动。", age: "0-16", free: true, io: "indoor", addr: "福田区福中一路2001号", tags: ["少儿区", "空调"] },
  { n: "深圳少年儿童图书馆", c: "library", city: "深圳", lat: 22.564, lng: 114.108, d: "专为儿童设计的图书馆，绘本区与故事会活动多。", age: "0-14", free: true, io: "indoor", addr: "罗湖区太宁路1号", tags: ["绘本", "故事会"] },
  { n: "深圳博物馆（历史民俗馆）", c: "museum", city: "深圳", lat: 22.543, lng: 114.062, d: "免费市博物馆，深圳改革开放史与民俗展，周末常有儿童讲解活动。", age: "4-16", free: true, io: "indoor", addr: "福田区市民中心A区", tags: ["历史"] },
  { n: "深圳野生动物园", c: "zoo", city: "深圳", lat: 22.593, lng: 113.985, d: "放养式动物园，可近距离看长颈鹿、火烈鸟，有动物表演。", age: "1-14", free: false, io: "outdoor", addr: "南山区西丽湖路4065号", tags: ["动物", "投喂"] },
  { n: "深圳欢乐谷", c: "themepark", city: "深圳", lat: 22.540, lng: 113.977, d: "大型主题乐园，过山车与儿童区兼备，暑期有夜场。", age: "3-16", free: false, io: "both", addr: "南山区侨城西街18号", tags: ["过山车", "演出"] },
  { n: "世界之窗", c: "themepark", city: "深圳", lat: 22.535, lng: 113.973, d: "世界地标微缩景观，晚间有大型演出与烟火。", age: "4-16", free: false, io: "outdoor", addr: "南山区深南大道9037号", tags: ["景观", "演出"] },
  { n: "东部华侨城", c: "themepark", city: "深圳", lat: 22.606, lng: 114.283, d: "山地主题乐园，茶溪谷+大侠谷，缆车与山间小火车。", age: "4-16", free: false, io: "outdoor", addr: "盐田区大梅沙东部华侨城", tags: ["缆车", "山景"] },
  { n: "大梅沙海滨公园", c: "beach", city: "深圳", lat: 22.596, lng: 114.313, d: "免费城市沙滩，设施成熟，旺季需预约。", age: "0-14", free: true, io: "outdoor", addr: "盐田区盐梅路9号", tags: ["沙滩", "需预约"] },
  { n: "较场尾海滩", c: "beach", city: "深圳", lat: 22.588, lng: 114.510, d: "大鹏民宿海滩村，沙质细，适合亲子过夜短途游。", age: "0-14", free: true, io: "outdoor", addr: "大鹏新区较场尾", tags: ["民宿", "沙滩"] },
  { n: "西涌沙滩", c: "beach", city: "深圳", lat: 22.478, lng: 114.548, d: "深圳最长海滩，暗夜社区可观星，水清人少。", age: "3-16", free: false, io: "outdoor", addr: "大鹏新区南澳西涌", tags: ["观星", "沙滩"] },
  { n: "梧桐山国家级风景区", c: "hiking", city: "深圳", lat: 22.586, lng: 114.209, d: "深圳第一峰，适合大童登山，秀桐道较缓可推车段少。", age: "6-16", free: true, io: "outdoor", addr: "罗湖区梧桐山", tags: ["登山", "云海"] },
  { n: "塘朗山郊野公园", c: "hiking", city: "深圳", lat: 22.559, lng: 113.985, d: "缓坡郊野绿道，山顶可望深圳湾，亲子入门徒步线。", age: "4-14", free: true, io: "outdoor", addr: "南山区龙珠六路", tags: ["绿道", "入门徒步"] },
  { n: "马峦山郊野公园", c: "hiking", city: "深圳", lat: 22.633, lng: 114.325, d: "深圳少有的瀑布溪谷徒步线，夏天可玩水。", age: "5-16", free: true, io: "outdoor", addr: "坪山区马峦山", tags: ["瀑布", "溪谷"] },
  { n: "光明农场大观园", c: "farm", city: "深圳", lat: 22.749, lng: 113.918, d: "奶牛示范基地，挤奶体验、喂小动物与滑草。", age: "2-12", free: false, io: "outdoor", addr: "光明区光明街道碧水路", tags: ["奶牛", "滑草"], season: "全年" },
  { n: "甘坑古镇", c: "park", city: "深圳", lat: 22.634, lng: 114.116, d: "客家小镇，小凉帽主题亲子业态，古建筑好拍照。", age: "2-12", free: true, io: "both", addr: "龙岗区甘坑社区", tags: ["古镇", "客家"] },
  { n: "杨梅坑", c: "hiking", city: "深圳", lat: 22.545, lng: 114.606, d: "海边骑行绿道与鹿嘴山庄步道，山海相接。", age: "4-16", free: true, io: "outdoor", addr: "大鹏新区南澳杨梅坑", tags: ["骑行", "海景"] },
  { n: "深圳海上世界", c: "park", city: "深圳", lat: 22.485, lng: 113.917, d: "明华轮广场音乐喷泉，滨海餐饮街区，傍晚遛娃佳。", age: "0-12", free: true, io: "outdoor", addr: "南山区蛇口望海路", tags: ["喷泉", "餐饮"] },

  // ============ 广州 ============
  { n: "长隆野生动物世界", c: "zoo", city: "广州", lat: 23.001, lng: 113.327, d: "亚洲顶级动物园，考拉、熊猫齐全，小火车穿越车行区。", age: "1-16", free: false, io: "outdoor", addr: "番禺区汉溪大道东299号", tags: ["熊猫", "小火车"] },
  { n: "长隆欢乐世界", c: "themepark", city: "广州", lat: 23.004, lng: 113.328, d: "大型游乐园，垂直过山车闻名，儿童区设施完善。", age: "3-16", free: false, io: "both", addr: "番禺区汉溪大道东", tags: ["过山车", "演出"] },
  { n: "长隆水上乐园", c: "waterplay", city: "广州", lat: 23.005, lng: 113.325, d: "全球客流量最大的水上乐园之一，亲子戏水区丰富。", age: "3-16", free: false, io: "outdoor", addr: "番禺区汉溪大道东", tags: ["滑道", "造浪池"] },
  { n: "广州动物园", c: "zoo", city: "广州", lat: 23.140, lng: 113.302, d: "市区老牌动物园，票价亲民，地铁直达。", age: "1-12", free: false, io: "outdoor", addr: "越秀区先烈中路120号", tags: ["市区", "亲民"] },
  { n: "正佳极地海洋世界", c: "zoo", city: "广州", lat: 23.132, lng: 113.327, d: "商场内的海洋馆，白鲸与企鹅，雨天遛娃好去处。", age: "1-12", free: false, io: "indoor", addr: "天河区天河路228号正佳广场", tags: ["白鲸", "室内"] },
  { n: "广州图书馆", c: "library", city: "广州", lat: 23.109, lng: 113.324, d: "花城广场地标图书馆，少儿部超大，需预约入馆。", age: "0-16", free: true, io: "indoor", addr: "天河区珠江东路4号", tags: ["少儿部", "地标"] },
  { n: "广州少年儿童图书馆", c: "library", city: "广州", lat: 23.127, lng: 113.267, d: "专门的少儿图书馆，分龄阅读区与常设故事活动。", age: "0-14", free: true, io: "indoor", addr: "越秀区中山四路42号", tags: ["分龄", "故事会"] },
  { n: "广东省博物馆", c: "museum", city: "广州", lat: 23.113, lng: 113.323, d: "月光宝盒造型省博，恐龙化石与海洋展厅孩子最爱。", age: "3-16", free: true, io: "indoor", addr: "天河区珠江东路2号", tags: ["恐龙", "需预约"] },
  { n: "广东科学中心", c: "museum", city: "广州", lat: 23.043, lng: 113.365, d: "亚洲特大科技馆，互动实验展项极多，可玩一整天。", age: "3-16", free: false, io: "indoor", addr: "番禺区科普路168号", tags: ["互动", "IMAX"] },
  { n: "越秀公园", c: "park", city: "广州", lat: 23.140, lng: 113.263, d: "五羊雕像所在的百年公园，湖泊山丘与大草坪。", age: "0-12", free: true, io: "outdoor", addr: "越秀区解放北路988号", tags: ["五羊", "湖景"] },
  { n: "天河公园", c: "park", city: "广州", lat: 23.126, lng: 113.365, d: "市区大型免费公园，湖边草坪适合野餐帐篷。", age: "0-12", free: true, io: "outdoor", addr: "天河区黄埔大道员村", tags: ["野餐", "草坪"] },
  { n: "海珠湖公园", c: "park", city: "广州", lat: 23.075, lng: 113.322, d: "广州塔旁的城市绿心，环湖步道平缓适合童车。", age: "0-12", free: true, io: "outdoor", addr: "海珠区新滘中路", tags: ["环湖", "花海"] },
  { n: "海珠国家湿地公园", c: "hiking", city: "广州", lat: 23.070, lng: 113.345, d: "城央湿地，果林与观鸟塔，自然教育课程丰富。", age: "3-14", free: false, io: "outdoor", addr: "海珠区新滘东路", tags: ["湿地", "自然教育"] },
  { n: "白云山风景区", c: "hiking", city: "广州", lat: 23.180, lng: 113.293, d: "羊城第一秀，缆车上山亲子友好，山顶广场开阔。", age: "3-16", free: false, io: "outdoor", addr: "白云区广园中路", tags: ["缆车", "登山"] },
  { n: "华南国家植物园", c: "park", city: "广州", lat: 23.186, lng: 113.362, d: "国家级植物园，温室群与凤梨园，自然课堂常年开放。", age: "2-14", free: false, io: "outdoor", addr: "天河区天源路1190号", tags: ["温室", "科普"] },
  { n: "广州市儿童公园", c: "playground", city: "广州", lat: 23.183, lng: 113.264, d: "免费大型儿童公园，沙池、戏水区与游乐设施分龄设置。", age: "0-12", free: true, io: "outdoor", addr: "白云区齐心路61号", tags: ["沙池", "戏水"] },
  { n: "二沙岛艺术公园", c: "park", city: "广州", lat: 23.112, lng: 113.305, d: "珠江中的安静小岛，大草坪与雕塑，适合野餐骑行。", age: "0-12", free: true, io: "outdoor", addr: "越秀区二沙岛", tags: ["草坪", "江景"] },
  { n: "广州融创乐园", c: "themepark", city: "广州", lat: 23.428, lng: 113.163, d: "花都大型乐园，另有室内滑雪场与水世界。", age: "3-16", free: false, io: "both", addr: "花都区凤凰北路", tags: ["滑雪", "水乐园"] },
  { n: "石门国家森林公园", c: "hiking", city: "广州", lat: 23.669, lng: 113.767, d: "从化天然氧吧，春赏花秋赏红叶，溪流步道。", age: "4-16", free: false, io: "outdoor", addr: "从化区温泉镇", tags: ["森林", "赏花"] },
  { n: "白水寨风景名胜区", c: "hiking", city: "广州", lat: 23.436, lng: 113.850, d: "内地落差最大瀑布之一，9999级登山步道可量力而行。", age: "5-16", free: false, io: "outdoor", addr: "增城区派潭镇", tags: ["瀑布", "登山"] },
  { n: "南沙湿地公园", c: "hiking", city: "广州", lat: 22.620, lng: 113.640, d: "珠三角候鸟天堂，坐船游湿地，冬季观鸟最佳。", age: "3-14", free: false, io: "outdoor", addr: "南沙区万顷沙镇", tags: ["观鸟", "游船"] },
  { n: "从化溪头村", c: "farm", city: "广州", lat: 23.727, lng: 113.729, d: "长寿村徒步与季节性水果采摘，夏季李子冬季砂糖橘。", age: "3-14", free: true, io: "outdoor", addr: "从化区良口镇溪头村", tags: ["采摘", "古村"], season: "6-8月李子 / 11-1月柑橘" },

  // ============ 香港 ============
  { n: "香港迪士尼乐园", c: "themepark", city: "香港", lat: 22.313, lng: 114.041, d: "亚洲经典迪士尼，冰雪奇缘园区人气高，烟花压轴。", age: "2-16", free: false, io: "both", addr: "大屿山迪士尼乐园度假区", tags: ["迪士尼", "烟花"] },
  { n: "香港海洋公园", c: "themepark", city: "香港", lat: 22.246, lng: 114.176, d: "山海主题乐园，大熊猫馆与海洋馆，缆车跨山海景震撼。", age: "2-16", free: false, io: "both", addr: "香港仔黄竹坑道180号", tags: ["熊猫", "缆车", "海洋馆"] },
  { n: "海洋公园水上乐园", c: "waterplay", city: "香港", lat: 22.247, lng: 114.180, d: "全天候临海水上乐园，室内外滑道全年开放。", age: "3-16", free: false, io: "both", addr: "南区大树湾", tags: ["滑道", "全年开放"] },
  { n: "香港科学馆", c: "museum", city: "香港", lat: 22.301, lng: 114.177, d: "互动科学展馆，能量穿梭机装置经典，儿童天地适合幼儿。", age: "2-14", free: false, io: "indoor", addr: "尖沙咀东部科学馆道2号", tags: ["互动", "亲民票价"] },
  { n: "香港太空馆", c: "museum", city: "香港", lat: 22.294, lng: 114.172, d: "蛋形建筑天文馆，天象厅球幕电影不容错过。", age: "4-14", free: false, io: "indoor", addr: "尖沙咀梳士巴利道10号", tags: ["天文", "球幕"] },
  { n: "香港历史博物馆", c: "museum", city: "香港", lat: 22.301, lng: 114.176, d: "香港故事常设展，实景街道还原老香港。", age: "5-16", free: true, io: "indoor", addr: "尖沙咀漆咸道南100号", tags: ["历史"] },
  { n: "M+ 博物馆", c: "museum", city: "香港", lat: 22.302, lng: 114.159, d: "西九文化区当代视觉文化博物馆，海旁草坪可野餐。", age: "5-16", free: false, io: "both", addr: "西九龙文化区博物馆道38号", tags: ["艺术", "海景草坪"] },
  { n: "香港湿地公园", c: "hiking", city: "香港", lat: 22.469, lng: 114.005, d: "天水围湿地保护区，观鸟屋与红树林浮桥，科普性强。", age: "3-14", free: false, io: "both", addr: "新界天水围湿地公园路", tags: ["湿地", "观鸟"] },
  { n: "香港中央图书馆", c: "library", city: "香港", lat: 22.280, lng: 114.190, d: "全港最大公共图书馆，玩具图书馆需预约。", age: "0-16", free: true, io: "indoor", addr: "铜锣湾高士威道66号", tags: ["玩具图书馆"] },
  { n: "九龙公园", c: "park", city: "香港", lat: 22.300, lng: 114.170, d: "闹市绿洲，火烈鸟池与大型儿童游乐场。", age: "0-12", free: true, io: "outdoor", addr: "尖沙咀柯士甸道22号", tags: ["火烈鸟", "游乐场"] },
  { n: "香港公园", c: "park", city: "香港", lat: 22.277, lng: 114.161, d: "中环山坡公园，观鸟园大型雀笼漫步道免费。", age: "0-12", free: true, io: "outdoor", addr: "中区红棉路19号", tags: ["观鸟园"] },
  { n: "维多利亚公园", c: "park", city: "香港", lat: 22.282, lng: 114.189, d: "港岛最大公园，游乐场与草坪，节庆花市热闹。", age: "0-12", free: true, io: "outdoor", addr: "铜锣湾兴发街1号", tags: ["草坪", "游乐场"] },
  { n: "浅水湾泳滩", c: "beach", city: "香港", lat: 22.237, lng: 114.197, d: "港岛经典泳滩，沙细浪缓，配套成熟。", age: "0-14", free: true, io: "outdoor", addr: "南区浅水湾海滩道", tags: ["泳滩", "救生员"] },
  { n: "石澳泳滩", c: "beach", city: "香港", lat: 22.231, lng: 114.253, d: "港岛东南小村泳滩，彩色小屋好拍照。", age: "2-14", free: true, io: "outdoor", addr: "南区石澳村", tags: ["泳滩", "拍照"] },
  { n: "清水湾二滩", c: "beach", city: "香港", lat: 22.281, lng: 114.297, d: "西贡清水质靓泳滩，周末家庭客多。", age: "2-14", free: true, io: "outdoor", addr: "西贡清水湾道", tags: ["水清", "泳滩"] },
  { n: "昂坪360与大佛", c: "hiking", city: "香港", lat: 22.256, lng: 113.905, d: "水晶缆车俯瞰大屿山，天坛大佛与昂坪市集。", age: "3-16", free: false, io: "both", addr: "大屿山昂坪", tags: ["缆车", "大佛"] },
  { n: "龙脊远足径", c: "hiking", city: "香港", lat: 22.245, lng: 114.238, d: "亚洲最佳市区远足径之一，山脊海景线，适合大童。", age: "7-16", free: true, io: "outdoor", addr: "港岛石澳道起步", tags: ["远足", "海景"] },
  { n: "塔门岛", c: "camping", city: "香港", lat: 22.472, lng: 114.360, d: "大草坪海岛露营胜地，看牛看海观星，需坐船。", age: "4-16", free: true, io: "outdoor", addr: "西贡塔门", tags: ["露营", "海岛"] },
  { n: "嘉道理农场暨植物园", c: "farm", city: "香港", lat: 22.432, lng: 114.117, d: "山地生态农场，动物救助站与有机农田，自然教育典范。", age: "3-14", free: false, io: "outdoor", addr: "大埔林锦公路", tags: ["生态", "动物"], season: "全年" },
  { n: "挪亚方舟主题公园", c: "themepark", city: "香港", lat: 22.352, lng: 114.059, d: "马湾1:1方舟建筑，亲子互动展馆与户外攀爬。", age: "2-12", free: false, io: "both", addr: "马湾珀欣路33号", tags: ["方舟", "互动"] },
  { n: "香港动植物公园", c: "zoo", city: "香港", lat: 22.277, lng: 114.156, d: "中环免费百年动植物公园，红毛猩猩与狐猴。", age: "0-12", free: true, io: "outdoor", addr: "中区雅宾利道", tags: ["灵长类"] },

  // ============ 澳门 ============
  { n: "澳门科学馆", c: "museum", city: "澳门", lat: 22.185, lng: 113.557, d: "贝聿铭设计的海滨科学馆，互动展厅分龄清晰。", age: "2-14", free: false, io: "indoor", addr: "澳门孙逸仙大马路", tags: ["互动", "天文馆"] },
  { n: "石排湾郊野公园与大熊猫馆", c: "zoo", city: "澳门", lat: 22.125, lng: 113.559, d: "路环山脚郊野公园，大熊猫馆票价亲民，另有动物区。", age: "0-12", free: false, io: "both", addr: "路环石排湾大马路", tags: ["熊猫", "亲民"] },
  { n: "黑沙海滩", c: "beach", city: "澳门", lat: 22.118, lng: 113.576, d: "澳门最大天然海滩，黑色海沙独特，旁有烧烤区。", age: "0-14", free: true, io: "outdoor", addr: "路环黑沙马路", tags: ["黑沙", "烧烤"] },
  { n: "龙环葡韵", c: "museum", city: "澳门", lat: 22.153, lng: 113.558, d: "五栋薄荷绿葡式别墅与湿地，展馆免费，白鹭常驻。", age: "2-12", free: true, io: "both", addr: "氹仔海边马路", tags: ["葡式建筑"] },
  { n: "氹仔中央公园", c: "park", city: "澳门", lat: 22.155, lng: 113.555, d: "氹仔居民区大公园，儿童游乐场设施新。", age: "0-10", free: true, io: "outdoor", addr: "氹仔成都街", tags: ["游乐场"] },
  { n: "二龙喉公园与松山缆车", c: "park", city: "澳门", lat: 22.200, lng: 113.548, d: "号称全球最短缆车上松山，山顶灯塔与炮台。", age: "2-12", free: true, io: "outdoor", addr: "澳门士多鸟拜斯大马路", tags: ["缆车", "灯塔"] },
  { n: "澳门海事博物馆", c: "museum", city: "澳门", lat: 22.186, lng: 113.531, d: "妈阁庙旁的航海历史博物馆，船模与互动展品。", age: "3-12", free: false, io: "indoor", addr: "妈阁上街1号", tags: ["航海", "亲民"] },
  { n: "teamLab 超自然空间", c: "indoorplay", city: "澳门", lat: 22.147, lng: 113.563, d: "威尼斯人旁沉浸式数字艺术空间，光影互动孩子着迷。", age: "2-14", free: false, io: "indoor", addr: "路氹金光大道", tags: ["光影", "沉浸式"] },

  // ============ 珠海 ============
  { n: "珠海长隆海洋王国", c: "themepark", city: "珠海", lat: 22.101, lng: 113.529, d: "世界级海洋主题乐园，鲸鲨馆与烟花汇演。", age: "1-16", free: false, io: "both", addr: "横琴新区富祥湾", tags: ["鲸鲨", "烟花"] },
  { n: "长隆宇宙飞船", c: "zoo", city: "珠海", lat: 22.104, lng: 113.532, d: "飞船造型超大室内海洋科学乐园，雨天遛娃首选。", age: "1-14", free: false, io: "indoor", addr: "横琴新区环岛东路", tags: ["室内", "海洋科学"] },
  { n: "珠海渔女与情侣路", c: "park", city: "珠海", lat: 22.259, lng: 113.590, d: "珠海地标雕像，沿海步道适合童车与滑板车。", age: "0-12", free: true, io: "outdoor", addr: "香洲区情侣中路", tags: ["海滨", "地标"] },
  { n: "珠海海滨公园", c: "park", city: "珠海", lat: 22.253, lng: 113.578, d: "老牌免费海滨公园，大草坪与儿童游乐区。", age: "0-12", free: true, io: "outdoor", addr: "香洲区情侣中路", tags: ["草坪"] },
  { n: "珠海博物馆", c: "museum", city: "珠海", lat: 22.244, lng: 113.575, d: "海滨新馆，珠海历史与海洋文化展陈，免费预约。", age: "4-16", free: true, io: "indoor", addr: "香洲区情侣路", tags: ["海洋文化"] },
  { n: "淇澳岛红树林保护区", c: "hiking", city: "珠海", lat: 22.418, lng: 113.630, d: "红树林栈道与渔村，骑行环岛亲子友好。", age: "3-14", free: true, io: "outdoor", addr: "香洲区淇澳岛", tags: ["红树林", "骑行"] },
  { n: "板樟山健身步道", c: "hiking", city: "珠海", lat: 22.263, lng: 113.560, d: "森林山脊步道与观景平台，可俯瞰珠澳两地。", age: "5-14", free: true, io: "outdoor", addr: "香洲区板樟山", tags: ["步道", "观景"] },
  { n: "香山湖公园", c: "park", city: "珠海", lat: 22.267, lng: 113.528, d: "山水相依的新公园，环湖绿道与大草坪。", age: "0-12", free: true, io: "outdoor", addr: "香洲区梅华东路", tags: ["环湖", "草坪"] },
  { n: "东澳岛", c: "beach", city: "珠海", lat: 22.014, lng: 113.710, d: "万山群岛度假海岛，南沙湾水质清澈，需乘船。", age: "3-14", free: false, io: "outdoor", addr: "万山区东澳岛", tags: ["海岛", "度假"] },
  { n: "外伶仃岛", c: "beach", city: "珠海", lat: 22.112, lng: 114.023, d: "离岛观海胜地，石景山步道可望香港，海鲜出名。", age: "4-14", free: false, io: "outdoor", addr: "万山区外伶仃岛", tags: ["海岛", "步道"] },
  { n: "珠海图书馆", c: "library", city: "珠海", lat: 22.271, lng: 113.567, d: "市级图书馆少儿区宽敞，周末讲座活动多。", age: "0-16", free: true, io: "indoor", addr: "香洲区迎宾北路", tags: ["少儿区"] },

  // ============ 佛山 ============
  { n: "千灯湖公园", c: "park", city: "佛山", lat: 23.037, lng: 113.140, d: "南海中轴水景公园，夜晚灯光秀，草坪开阔。", age: "0-12", free: true, io: "outdoor", addr: "南海区桂澜北路", tags: ["夜景", "草坪"] },
  { n: "佛山市图书馆", c: "library", city: "佛山", lat: 23.007, lng: 113.147, d: "佛山新城大型图书馆，少儿馆有专属活动空间。", age: "0-16", free: true, io: "indoor", addr: "顺德区乐从镇华康道", tags: ["少儿馆"] },
  { n: "南风古灶", c: "museum", city: "佛山", lat: 23.005, lng: 113.093, d: "五百年龙窑活文物，陶艺拉坯亲子体验。", age: "3-14", free: false, io: "both", addr: "禅城区石湾高庙路", tags: ["陶艺", "体验"] },
  { n: "西樵山风景区", c: "hiking", city: "佛山", lat: 22.930, lng: 112.960, d: "岭南名山，观音文化与山湖步道，缆车可达。", age: "4-16", free: false, io: "outdoor", addr: "南海区西樵镇", tags: ["名山", "缆车"] },
  { n: "长鹿旅游休博园", c: "themepark", city: "佛山", lat: 22.821, lng: 113.279, d: "顺德老牌亲子乐园，动物园+机动游戏+农家体验。", age: "1-14", free: false, io: "both", addr: "顺德区伦教镇", tags: ["动物", "机动游戏"] },
  { n: "顺德欢乐海岸PLUS", c: "themepark", city: "佛山", lat: 22.818, lng: 113.255, d: "水岸乐园与玛雅水公园，摩天轮夜景美。", age: "2-14", free: false, io: "both", addr: "顺德区大良街道", tags: ["水乐园", "摩天轮"] },
  { n: "亚洲艺术公园", c: "park", city: "佛山", lat: 23.019, lng: 113.124, d: "禅城水上公园，桥廊水景与大片草坪。", age: "0-12", free: true, io: "outdoor", addr: "禅城区文华北路", tags: ["水景"] },
  { n: "三水荷花世界", c: "park", city: "佛山", lat: 23.175, lng: 112.905, d: "夏季赏荷主题园，荷花季亲子写生好去处。", age: "2-12", free: false, io: "outdoor", addr: "三水区西南街道", tags: ["荷花", "夏季"] },
  { n: "盈香生态园", c: "farm", city: "佛山", lat: 22.850, lng: 112.800, d: "高明综合生态园，四季花海、采摘与机动游戏。", age: "2-14", free: false, io: "outdoor", addr: "高明区荷城街道冼村", tags: ["花海", "采摘"], season: "全年花期轮换" },
  { n: "美的鹭湖水世界", c: "waterplay", city: "佛山", lat: 22.798, lng: 112.752, d: "高明度假区水乐园，另有探索王国与温泉。", age: "3-14", free: false, io: "outdoor", addr: "高明区杨和镇", tags: ["水乐园", "度假"] },

  // ============ 东莞 ============
  { n: "松山湖景区", c: "park", city: "东莞", lat: 22.925, lng: 113.878, d: "环湖绿道骑行圣地，春季黄花风铃木刷屏。", age: "0-14", free: true, io: "outdoor", addr: "松山湖高新区", tags: ["骑行", "赏花"] },
  { n: "东莞植物园", c: "park", city: "东莞", lat: 23.005, lng: 113.745, d: "免费大型植物园，专类园与大草坪适合野餐。", age: "0-12", free: true, io: "outdoor", addr: "南城街道绿色路", tags: ["野餐"] },
  { n: "东莞市科学技术博物馆", c: "museum", city: "东莞", lat: 23.020, lng: 113.752, d: "制造业主题科技馆，机器人展项有特色。", age: "3-14", free: true, io: "indoor", addr: "南城街道元美路2号", tags: ["机器人"] },
  { n: "海战博物馆", c: "museum", city: "东莞", lat: 22.805, lng: 113.652, d: "虎门销烟与鸦片战争史，海边炮台遗址可散步。", age: "5-16", free: true, io: "both", addr: "虎门镇威远岛", tags: ["历史"] },
  { n: "银瓶山森林公园", c: "hiking", city: "东莞", lat: 22.940, lng: 114.190, d: "东莞第一峰，溪谷步道前段平缓适合亲子。", age: "4-16", free: true, io: "outdoor", addr: "谢岗镇银瓶山", tags: ["溪谷", "登山"] },
  { n: "隐贤山庄", c: "themepark", city: "东莞", lat: 22.975, lng: 113.975, d: "常平综合乐园，机动游戏与动物互动，性价比高。", age: "2-14", free: false, io: "both", addr: "常平镇丽城", tags: ["性价比", "动物"] },
  { n: "华阳湖国家湿地公园", c: "hiking", city: "东莞", lat: 23.033, lng: 113.555, d: "麻涌水乡湿地，绿道骑行与游船看夕阳。", age: "2-14", free: true, io: "outdoor", addr: "麻涌镇", tags: ["湿地", "骑行"] },
  { n: "东莞图书馆", c: "library", city: "东莞", lat: 23.019, lng: 113.752, d: "24小时自助图书馆先行者，绘本馆藏丰富。", age: "0-16", free: true, io: "indoor", addr: "南城街道新芬路", tags: ["绘本"] },
  { n: "香市动物园", c: "zoo", city: "东莞", lat: 22.965, lng: 113.836, d: "寮步中型动物园，动物表演与投喂体验，票价亲民。", age: "1-12", free: false, io: "outdoor", addr: "寮步镇药勒村", tags: ["投喂", "亲民"] },

  // ============ 中山 ============
  { n: "中山詹园", c: "park", city: "中山", lat: 22.445, lng: 113.350, d: "岭南最大私家园林，古典建筑与孝道文化。", age: "3-14", free: false, io: "both", addr: "南区北台村", tags: ["园林", "古典"] },
  { n: "孙中山故里旅游区", c: "museum", city: "中山", lat: 22.410, lng: 113.443, d: "翠亨村故居与纪念馆，历史人文研学线路。", age: "5-16", free: true, io: "both", addr: "南朗街道翠亨村", tags: ["历史", "研学"] },
  { n: "金钟湖公园", c: "park", city: "中山", lat: 22.530, lng: 113.400, d: "环湖步道与儿童乐园，中山市民后花园。", age: "0-12", free: true, io: "outdoor", addr: "东区金钟大道", tags: ["环湖"] },
  { n: "紫马岭公园", c: "park", city: "中山", lat: 22.518, lng: 113.405, d: "老牌市政公园，鸟语林与大片绿地。", age: "0-12", free: true, io: "outdoor", addr: "东区中山五路", tags: ["鸟语林"] },
  { n: "中山纪念图书馆", c: "library", city: "中山", lat: 22.515, lng: 113.390, d: "现代化市图书馆，少儿区与亲子自习空间大。", age: "0-16", free: true, io: "indoor", addr: "东区兴中道8号", tags: ["少儿区"] },
  { n: "中山影视城", c: "themepark", city: "中山", lat: 22.413, lng: 113.442, d: "民国主题影视基地，实景演出与服装体验。", age: "4-14", free: false, io: "both", addr: "南朗街道翠亨村", tags: ["民国", "演出"] },

  // ============ 惠州 ============
  { n: "惠州西湖风景区", c: "park", city: "惠州", lat: 23.095, lng: 114.400, d: "国家5A湖泊景区，免费开放，泗洲塔与九曲桥。", age: "0-14", free: true, io: "outdoor", addr: "惠城区环城西路", tags: ["5A"] },
  { n: "红花湖景区", c: "hiking", city: "惠州", lat: 23.072, lng: 114.378, d: "18公里环湖绿道，租自行车环湖是经典亲子项目。", age: "3-14", free: true, io: "outdoor", addr: "惠城区红花湖路", tags: ["骑行", "绿道"] },
  { n: "巽寮湾", c: "beach", city: "惠州", lat: 22.705, lng: 114.745, d: "惠东经典海湾，沙滩平缓，出海捕鱼体验多。", age: "0-14", free: true, io: "outdoor", addr: "惠东县巽寮镇", tags: ["沙滩", "出海"] },
  { n: "双月湾", c: "beach", city: "惠州", lat: 22.570, lng: 114.884, d: "两湾相连如双月，观景台看日出日落，海龟保护区在侧。", age: "2-14", free: true, io: "outdoor", addr: "惠东县港口镇", tags: ["观景台", "海龟"] },
  { n: "罗浮山风景区", c: "hiking", city: "惠州", lat: 23.275, lng: 114.053, d: "岭南第一山，索道上山，道教文化与飞瀑。", age: "4-16", free: false, io: "outdoor", addr: "博罗县长宁镇", tags: ["索道", "名山"] },
  { n: "南昆山生态旅游区", c: "camping", city: "惠州", lat: 23.634, lng: 113.853, d: "北回归线上的绿洲，竹林溪流，夏季避暑露营地多。", age: "3-14", free: false, io: "outdoor", addr: "龙门县南昆山", tags: ["避暑", "竹林"] },
  { n: "惠州科技馆", c: "museum", city: "惠州", lat: 23.088, lng: 114.418, d: "免费市级科技馆，基础科学互动展项。", age: "3-14", free: true, io: "indoor", addr: "惠城区江北文华一路", tags: ["互动"] },

  // ============ 江门 ============
  { n: "开平碉楼（自力村）", c: "museum", city: "江门", lat: 22.290, lng: 112.555, d: "世界文化遗产，中西合璧碉楼群，稻田风光。", age: "4-16", free: false, io: "outdoor", addr: "开平市塘口镇", tags: ["世遗", "碉楼"] },
  { n: "小鸟天堂", c: "hiking", city: "江门", lat: 22.512, lng: 113.075, d: "巴金笔下的独木成林，坐船观万鸟归巢。", age: "2-12", free: false, io: "outdoor", addr: "新会区会城街道", tags: ["观鸟", "游船"] },
  { n: "圭峰山国家森林公园", c: "hiking", city: "江门", lat: 22.610, lng: 113.055, d: "新会绿肺，玉台寺与登山步道，山脚绿道平缓。", age: "3-14", free: true, io: "outdoor", addr: "新会区圭峰路", tags: ["森林", "登山"] },
  { n: "古兜温泉小镇", c: "waterplay", city: "江门", lat: 22.210, lng: 112.935, d: "山海温泉度假区，夏有水世界冬泡温泉。", age: "2-14", free: false, io: "both", addr: "新会区崖门镇", tags: ["温泉", "水世界"] },
  { n: "五邑华侨华人博物馆", c: "museum", city: "江门", lat: 22.578, lng: 113.080, d: "华侨史主题博物馆，了解五邑侨乡故事。", age: "5-16", free: true, io: "indoor", addr: "蓬江区港口路", tags: ["华侨"] },
  { n: "上川岛飞沙滩", c: "beach", city: "江门", lat: 21.740, lng: 112.775, d: "广东知名海岛沙滩，需乘船上岛，水清沙幼。", age: "3-14", free: false, io: "outdoor", addr: "台山市川岛镇", tags: ["海岛", "沙滩"] },

  // ============ 肇庆 ============
  { n: "七星岩风景区", c: "park", city: "肇庆", lat: 23.060, lng: 112.460, d: "喀斯特湖岩景观，湖上石峰如北斗，游船环湖。", age: "2-14", free: false, io: "outdoor", addr: "端州区七星路", tags: ["喀斯特", "游船"] },
  { n: "鼎湖山风景区", c: "hiking", city: "肇庆", lat: 23.160, lng: 112.540, d: "北回归线绿宝石，负离子森林与蝴蝶谷飞水潭。", age: "3-14", free: false, io: "outdoor", addr: "鼎湖区上山路", tags: ["森林", "瀑布"] },
  { n: "肇庆牌坊公园", c: "park", city: "肇庆", lat: 23.047, lng: 112.465, d: "星湖旁市民广场，音乐喷泉夜晚开放。", age: "0-12", free: true, io: "outdoor", addr: "端州区天宁北路", tags: ["喷泉"] },
  { n: "紫云谷风景区", c: "waterplay", city: "肇庆", lat: 23.033, lng: 112.528, d: "西江畔溪谷景区，夏季天然山水泳池玩水胜地。", age: "3-14", free: false, io: "outdoor", addr: "端州区羚羊峡", tags: ["溪谷", "玩水"] },
];
